//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    
    
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2
    {
        
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 423, "municipality", "municipalities")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 423, "municipalité")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("sl", "slv", 423, "občina")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 497, "urban municipality", "urban municipalities")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 497, "municipalité urbaine")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("sl", "slv", 497, "mestna občina")]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("sl", "slv", IsAdministrative=true)]
        public static class SI
        {
            
            #region municipalities
            /// <summary>
            /// Ig
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-037")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ig")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _037 = new DataStandardizer.ISO3166.Iso3166Part2("SI-037");
            
            /// <summary>
            /// Škofljica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-123")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Škofljica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _123 = new DataStandardizer.ISO3166.Iso3166Part2("SI-123");
            
            /// <summary>
            /// Šmartno ob Paki
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-125")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šmartno ob Paki")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _125 = new DataStandardizer.ISO3166.Iso3166Part2("SI-125");
            
            /// <summary>
            /// Škofja Loka
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-122")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Škofja Loka")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _122 = new DataStandardizer.ISO3166.Iso3166Part2("SI-122");
            
            /// <summary>
            /// Škocjan
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-121")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Škocjan")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _121 = new DataStandardizer.ISO3166.Iso3166Part2("SI-121");
            
            /// <summary>
            /// Šentjur
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-120")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šentjur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _120 = new DataStandardizer.ISO3166.Iso3166Part2("SI-120");
            
            /// <summary>
            /// Šentjernej
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-119")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šentjernej")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _119 = new DataStandardizer.ISO3166.Iso3166Part2("SI-119");
            
            /// <summary>
            /// Šmarje pri Jelšah
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-124")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šmarje pri Jelšah")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _124 = new DataStandardizer.ISO3166.Iso3166Part2("SI-124");
            
            /// <summary>
            /// Šoštanj
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-126")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šoštanj")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _126 = new DataStandardizer.ISO3166.Iso3166Part2("SI-126");
            
            /// <summary>
            /// Trbovlje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-129")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Trbovlje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _129 = new DataStandardizer.ISO3166.Iso3166Part2("SI-129");
            
            /// <summary>
            /// Tolmin
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-128")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Tolmin")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _128 = new DataStandardizer.ISO3166.Iso3166Part2("SI-128");
            
            /// <summary>
            /// Vojnik
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-139")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Vojnik")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _139 = new DataStandardizer.ISO3166.Iso3166Part2("SI-139");
            
            /// <summary>
            /// Kamnik
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-043")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kamnik")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _043 = new DataStandardizer.ISO3166.Iso3166Part2("SI-043");
            
            /// <summary>
            /// Kanal ob Soči
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-044")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kanal ob Soči")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _044 = new DataStandardizer.ISO3166.Iso3166Part2("SI-044");
            
            /// <summary>
            /// Kidričevo
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-045")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kidričevo")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _045 = new DataStandardizer.ISO3166.Iso3166Part2("SI-045");
            
            /// <summary>
            /// Kobarid
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-046")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kobarid")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _046 = new DataStandardizer.ISO3166.Iso3166Part2("SI-046");
            
            /// <summary>
            /// Kobilje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-047")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kobilje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _047 = new DataStandardizer.ISO3166.Iso3166Part2("SI-047");
            
            /// <summary>
            /// Kočevje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-048")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kočevje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _048 = new DataStandardizer.ISO3166.Iso3166Part2("SI-048");
            
            /// <summary>
            /// Komen
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-049")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Komen")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _049 = new DataStandardizer.ISO3166.Iso3166Part2("SI-049");
            
            /// <summary>
            /// Kozje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-051")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kozje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _051 = new DataStandardizer.ISO3166.Iso3166Part2("SI-051");
            
            /// <summary>
            /// Kranjska Gora
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-053")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kranjska Gora")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _053 = new DataStandardizer.ISO3166.Iso3166Part2("SI-053");
            
            /// <summary>
            /// Kungota
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-055")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kungota")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _055 = new DataStandardizer.ISO3166.Iso3166Part2("SI-055");
            
            /// <summary>
            /// Kuzma
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-056")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kuzma")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _056 = new DataStandardizer.ISO3166.Iso3166Part2("SI-056");
            
            /// <summary>
            /// Laško
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-057")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Laško")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _057 = new DataStandardizer.ISO3166.Iso3166Part2("SI-057");
            
            /// <summary>
            /// Lenart
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-058")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Lenart")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _058 = new DataStandardizer.ISO3166.Iso3166Part2("SI-058");
            
            /// <summary>
            /// Štore
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-127")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Štore")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _127 = new DataStandardizer.ISO3166.Iso3166Part2("SI-127");
            
            /// <summary>
            /// Lendava
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-059")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Lendava", SubdivisionNameLocalVariant="Lendva")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _059 = new DataStandardizer.ISO3166.Iso3166Part2("SI-059");
            
            /// <summary>
            /// Vodice
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-138")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Vodice")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _138 = new DataStandardizer.ISO3166.Iso3166Part2("SI-138");
            
            /// <summary>
            /// Ljubno
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-062")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ljubno")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _062 = new DataStandardizer.ISO3166.Iso3166Part2("SI-062");
            
            /// <summary>
            /// Ljutomer
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-063")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ljutomer")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _063 = new DataStandardizer.ISO3166.Iso3166Part2("SI-063");
            
            /// <summary>
            /// Logatec
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-064")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Logatec")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _064 = new DataStandardizer.ISO3166.Iso3166Part2("SI-064");
            
            /// <summary>
            /// Loška dolina
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-065")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Loška dolina")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _065 = new DataStandardizer.ISO3166.Iso3166Part2("SI-065");
            
            /// <summary>
            /// Loški Potok
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-066")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Loški Potok")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _066 = new DataStandardizer.ISO3166.Iso3166Part2("SI-066");
            
            /// <summary>
            /// Vitanje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-137")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Vitanje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _137 = new DataStandardizer.ISO3166.Iso3166Part2("SI-137");
            
            /// <summary>
            /// Vipava
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-136")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Vipava")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _136 = new DataStandardizer.ISO3166.Iso3166Part2("SI-136");
            
            /// <summary>
            /// Videm
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-135")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Videm")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _135 = new DataStandardizer.ISO3166.Iso3166Part2("SI-135");
            
            /// <summary>
            /// Velike Lašče
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-134")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Velike Lašče")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _134 = new DataStandardizer.ISO3166.Iso3166Part2("SI-134");
            
            /// <summary>
            /// Turnišče
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-132")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Turnišče")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _132 = new DataStandardizer.ISO3166.Iso3166Part2("SI-132");
            
            /// <summary>
            /// Tržič
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-131")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Tržič")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _131 = new DataStandardizer.ISO3166.Iso3166Part2("SI-131");
            
            /// <summary>
            /// Trebnje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-130")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Trebnje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _130 = new DataStandardizer.ISO3166.Iso3166Part2("SI-130");
            
            /// <summary>
            /// Šentilj
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-118")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šentilj")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _118 = new DataStandardizer.ISO3166.Iso3166Part2("SI-118");
            
            /// <summary>
            /// Litija
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-060")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Litija")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _060 = new DataStandardizer.ISO3166.Iso3166Part2("SI-060");
            
            /// <summary>
            /// Šenčur
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-117")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šenčur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _117 = new DataStandardizer.ISO3166.Iso3166Part2("SI-117");
            
            /// <summary>
            /// Metlika
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-073")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Metlika")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _073 = new DataStandardizer.ISO3166.Iso3166Part2("SI-073");
            
            /// <summary>
            /// Starše
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-115")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Starše")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _115 = new DataStandardizer.ISO3166.Iso3166Part2("SI-115");
            
            /// <summary>
            /// Radeče
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-099")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Radeče")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _099 = new DataStandardizer.ISO3166.Iso3166Part2("SI-099");
            
            /// <summary>
            /// Rače-Fram
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-098")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Rače-Fram")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _098 = new DataStandardizer.ISO3166.Iso3166Part2("SI-098");
            
            /// <summary>
            /// Puconci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-097")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Puconci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _097 = new DataStandardizer.ISO3166.Iso3166Part2("SI-097");
            
            /// <summary>
            /// Preddvor
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-095")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Preddvor")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _095 = new DataStandardizer.ISO3166.Iso3166Part2("SI-095");
            
            /// <summary>
            /// Postojna
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-094")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Postojna")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _094 = new DataStandardizer.ISO3166.Iso3166Part2("SI-094");
            
            /// <summary>
            /// Mislinja
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-076")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Mislinja")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _076 = new DataStandardizer.ISO3166.Iso3166Part2("SI-076");
            
            /// <summary>
            /// Moravče
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-077")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Moravče")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _077 = new DataStandardizer.ISO3166.Iso3166Part2("SI-077");
            
            /// <summary>
            /// Moravske Toplice
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-078")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Moravske Toplice")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _078 = new DataStandardizer.ISO3166.Iso3166Part2("SI-078");
            
            /// <summary>
            /// Radenci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-100")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Radenci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _100 = new DataStandardizer.ISO3166.Iso3166Part2("SI-100");
            
            /// <summary>
            /// Podvelka
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-093")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Podvelka")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _093 = new DataStandardizer.ISO3166.Iso3166Part2("SI-093");
            
            /// <summary>
            /// Pivka
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-091")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Pivka")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _091 = new DataStandardizer.ISO3166.Iso3166Part2("SI-091");
            
            /// <summary>
            /// Piran
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-090")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Piran", SubdivisionNameLocalVariant="Pirano")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _090 = new DataStandardizer.ISO3166.Iso3166Part2("SI-090");
            
            /// <summary>
            /// Pesnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-089")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Pesnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _089 = new DataStandardizer.ISO3166.Iso3166Part2("SI-089");
            
            /// <summary>
            /// Osilnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-088")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Osilnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _088 = new DataStandardizer.ISO3166.Iso3166Part2("SI-088");
            
            /// <summary>
            /// Mozirje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-079")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Mozirje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _079 = new DataStandardizer.ISO3166.Iso3166Part2("SI-079");
            
            /// <summary>
            /// Muta
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-081")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Muta")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _081 = new DataStandardizer.ISO3166.Iso3166Part2("SI-081");
            
            /// <summary>
            /// Naklo
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-082")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Naklo")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _082 = new DataStandardizer.ISO3166.Iso3166Part2("SI-082");
            
            /// <summary>
            /// Nazarje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-083")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Nazarje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _083 = new DataStandardizer.ISO3166.Iso3166Part2("SI-083");
            
            /// <summary>
            /// Podčetrtek
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-092")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Podčetrtek")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _092 = new DataStandardizer.ISO3166.Iso3166Part2("SI-092");
            
            /// <summary>
            /// Sveti Jurij ob Ščavnici
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-116")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sveti Jurij ob Ščavnici")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _116 = new DataStandardizer.ISO3166.Iso3166Part2("SI-116");
            
            /// <summary>
            /// Radlje ob Dravi
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-101")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Radlje ob Dravi")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _101 = new DataStandardizer.ISO3166.Iso3166Part2("SI-101");
            
            /// <summary>
            /// Ravne na Koroškem
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-103")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ravne na Koroškem")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _103 = new DataStandardizer.ISO3166.Iso3166Part2("SI-103");
            
            /// <summary>
            /// Slovenske Konjice
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-114")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Slovenske Konjice")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _114 = new DataStandardizer.ISO3166.Iso3166Part2("SI-114");
            
            /// <summary>
            /// Slovenska Bistrica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-113")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Slovenska Bistrica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _113 = new DataStandardizer.ISO3166.Iso3166Part2("SI-113");
            
            /// <summary>
            /// Luče
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-067")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Luče")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _067 = new DataStandardizer.ISO3166.Iso3166Part2("SI-067");
            
            /// <summary>
            /// Lukovica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-068")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Lukovica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _068 = new DataStandardizer.ISO3166.Iso3166Part2("SI-068");
            
            /// <summary>
            /// Majšperk
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-069")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Majšperk")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _069 = new DataStandardizer.ISO3166.Iso3166Part2("SI-069");
            
            /// <summary>
            /// Medvode
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-071")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Medvode")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _071 = new DataStandardizer.ISO3166.Iso3166Part2("SI-071");
            
            /// <summary>
            /// Mengeš
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-072")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Mengeš")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _072 = new DataStandardizer.ISO3166.Iso3166Part2("SI-072");
            
            /// <summary>
            /// Juršinci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-042")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Juršinci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _042 = new DataStandardizer.ISO3166.Iso3166Part2("SI-042");
            
            /// <summary>
            /// Radovljica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-102")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Radovljica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _102 = new DataStandardizer.ISO3166.Iso3166Part2("SI-102");
            
            /// <summary>
            /// Mežica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-074")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Mežica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _074 = new DataStandardizer.ISO3166.Iso3166Part2("SI-074");
            
            /// <summary>
            /// Sežana
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-111")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sežana")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _111 = new DataStandardizer.ISO3166.Iso3166Part2("SI-111");
            
            /// <summary>
            /// Sevnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-110")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sevnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _110 = new DataStandardizer.ISO3166.Iso3166Part2("SI-110");
            
            /// <summary>
            /// Semič
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-109")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Semič")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _109 = new DataStandardizer.ISO3166.Iso3166Part2("SI-109");
            
            /// <summary>
            /// Ruše
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-108")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ruše")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _108 = new DataStandardizer.ISO3166.Iso3166Part2("SI-108");
            
            /// <summary>
            /// Rogatec
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-107")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Rogatec")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _107 = new DataStandardizer.ISO3166.Iso3166Part2("SI-107");
            
            /// <summary>
            /// Rogaška Slatina
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-106")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Rogaška Slatina")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _106 = new DataStandardizer.ISO3166.Iso3166Part2("SI-106");
            
            /// <summary>
            /// Rogašovci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-105")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Rogašovci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _105 = new DataStandardizer.ISO3166.Iso3166Part2("SI-105");
            
            /// <summary>
            /// Ribnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-104")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ribnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _104 = new DataStandardizer.ISO3166.Iso3166Part2("SI-104");
            
            /// <summary>
            /// Miren-Kostanjevica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-075")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Miren-Kostanjevica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _075 = new DataStandardizer.ISO3166.Iso3166Part2("SI-075");
            
            /// <summary>
            /// Jesenice
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-041")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Jesenice")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _041 = new DataStandardizer.ISO3166.Iso3166Part2("SI-041");
            
            /// <summary>
            /// Dol pri Ljubljani
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-022")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dol pri Ljubljani")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _022 = new DataStandardizer.ISO3166.Iso3166Part2("SI-022");
            
            /// <summary>
            /// Ivančna Gorica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-039")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ivančna Gorica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _039 = new DataStandardizer.ISO3166.Iso3166Part2("SI-039");
            
            /// <summary>
            /// Tabor
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-184")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Tabor")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _184 = new DataStandardizer.ISO3166.Iso3166Part2("SI-184");
            
            /// <summary>
            /// Šempeter-Vrtojba
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-183")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šempeter-Vrtojba")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _183 = new DataStandardizer.ISO3166.Iso3166Part2("SI-183");
            
            /// <summary>
            /// Sveti Andraž v Slovenskih goricah
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-182")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sveti Andraž v Slovenskih goricah")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _182 = new DataStandardizer.ISO3166.Iso3166Part2("SI-182");
            
            /// <summary>
            /// Sveta Ana
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-181")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sveta Ana")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _181 = new DataStandardizer.ISO3166.Iso3166Part2("SI-181");
            
            /// <summary>
            /// Solčava
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-180")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Solčava")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _180 = new DataStandardizer.ISO3166.Iso3166Part2("SI-180");
            
            /// <summary>
            /// Sodražica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-179")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sodražica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _179 = new DataStandardizer.ISO3166.Iso3166Part2("SI-179");
            
            /// <summary>
            /// Selnica ob Dravi
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-178")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Selnica ob Dravi")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _178 = new DataStandardizer.ISO3166.Iso3166Part2("SI-178");
            
            /// <summary>
            /// Ribnica na Pohorju
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-177")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ribnica na Pohorju")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _177 = new DataStandardizer.ISO3166.Iso3166Part2("SI-177");
            
            /// <summary>
            /// Razkrižje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-176")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Razkrižje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _176 = new DataStandardizer.ISO3166.Iso3166Part2("SI-176");
            
            /// <summary>
            /// Prevalje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-175")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Prevalje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _175 = new DataStandardizer.ISO3166.Iso3166Part2("SI-175");
            
            /// <summary>
            /// Prebold
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-174")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Prebold")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _174 = new DataStandardizer.ISO3166.Iso3166Part2("SI-174");
            
            /// <summary>
            /// Trnovska Vas
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-185")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Trnovska Vas")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _185 = new DataStandardizer.ISO3166.Iso3166Part2("SI-185");
            
            /// <summary>
            /// Polzela
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-173")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Polzela")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _173 = new DataStandardizer.ISO3166.Iso3166Part2("SI-173");
            
            /// <summary>
            /// Oplotnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-171")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Oplotnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _171 = new DataStandardizer.ISO3166.Iso3166Part2("SI-171");
            
            /// <summary>
            /// Mirna Peč
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-170")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Mirna Peč")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _170 = new DataStandardizer.ISO3166.Iso3166Part2("SI-170");
            
            /// <summary>
            /// Ajdovščina
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-001")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ajdovščina")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _001 = new DataStandardizer.ISO3166.Iso3166Part2("SI-001");
            
            /// <summary>
            /// Beltinci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-002")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Beltinci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _002 = new DataStandardizer.ISO3166.Iso3166Part2("SI-002");
            
            /// <summary>
            /// Bled
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-003")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Bled")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _003 = new DataStandardizer.ISO3166.Iso3166Part2("SI-003");
            
            /// <summary>
            /// Miklavž na Dravskem polju
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-169")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Miklavž na Dravskem polju")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _169 = new DataStandardizer.ISO3166.Iso3166Part2("SI-169");
            
            /// <summary>
            /// Bohinj
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-004")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Bohinj")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _004 = new DataStandardizer.ISO3166.Iso3166Part2("SI-004");
            
            /// <summary>
            /// Borovnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-005")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Borovnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _005 = new DataStandardizer.ISO3166.Iso3166Part2("SI-005");
            
            /// <summary>
            /// Bovec
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-006")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Bovec")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _006 = new DataStandardizer.ISO3166.Iso3166Part2("SI-006");
            
            /// <summary>
            /// Brda
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-007")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Brda")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _007 = new DataStandardizer.ISO3166.Iso3166Part2("SI-007");
            
            /// <summary>
            /// Brezovica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-008")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Brezovica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _008 = new DataStandardizer.ISO3166.Iso3166Part2("SI-008");
            
            /// <summary>
            /// Podlehnik
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-172")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Podlehnik")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _172 = new DataStandardizer.ISO3166.Iso3166Part2("SI-172");
            
            /// <summary>
            /// Trzin
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-186")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Trzin")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _186 = new DataStandardizer.ISO3166.Iso3166Part2("SI-186");
            
            /// <summary>
            /// Velika Polana
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-187")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Velika Polana")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _187 = new DataStandardizer.ISO3166.Iso3166Part2("SI-187");
            
            /// <summary>
            /// Veržej
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-188")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Veržej")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _188 = new DataStandardizer.ISO3166.Iso3166Part2("SI-188");
            
            /// <summary>
            /// Ankaran
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-213")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ankaran", SubdivisionNameLocalVariant="Ancarano")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _213 = new DataStandardizer.ISO3166.Iso3166Part2("SI-213");
            
            /// <summary>
            /// Mirna
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-212")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Mirna")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _212 = new DataStandardizer.ISO3166.Iso3166Part2("SI-212");
            
            /// <summary>
            /// Šentrupert
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-211")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šentrupert")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _211 = new DataStandardizer.ISO3166.Iso3166Part2("SI-211");
            
            /// <summary>
            /// Sveti Jurij v Slovenskih goricah
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-210")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sveti Jurij v Slovenskih goricah")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _210 = new DataStandardizer.ISO3166.Iso3166Part2("SI-210");
            
            /// <summary>
            /// Rečica ob Savinji
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-209")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Rečica ob Savinji")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _209 = new DataStandardizer.ISO3166.Iso3166Part2("SI-209");
            
            /// <summary>
            /// Log-Dragomer
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-208")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Log-Dragomer")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _208 = new DataStandardizer.ISO3166.Iso3166Part2("SI-208");
            
            /// <summary>
            /// Gorje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-207")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Gorje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _207 = new DataStandardizer.ISO3166.Iso3166Part2("SI-207");
            
            /// <summary>
            /// Šmarješke Toplice
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-206")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šmarješke Toplice")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _206 = new DataStandardizer.ISO3166.Iso3166Part2("SI-206");
            
            /// <summary>
            /// Sveti Tomaž
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-205")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sveti Tomaž")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _205 = new DataStandardizer.ISO3166.Iso3166Part2("SI-205");
            
            /// <summary>
            /// Sveta Trojica v Slovenskih goricah
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-204")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Sveta Trojica v Slovenskih goricah")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _204 = new DataStandardizer.ISO3166.Iso3166Part2("SI-204");
            
            /// <summary>
            /// Straža
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-203")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Straža")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _203 = new DataStandardizer.ISO3166.Iso3166Part2("SI-203");
            
            /// <summary>
            /// Središče ob Dravi
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-202")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Središče ob Dravi")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _202 = new DataStandardizer.ISO3166.Iso3166Part2("SI-202");
            
            /// <summary>
            /// Renče-Vogrsko
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-201")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Renče-Vogrsko")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _201 = new DataStandardizer.ISO3166.Iso3166Part2("SI-201");
            
            /// <summary>
            /// Poljčane
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-200")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Poljčane")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _200 = new DataStandardizer.ISO3166.Iso3166Part2("SI-200");
            
            /// <summary>
            /// Mokronog-Trebelno
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-199")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Mokronog-Trebelno")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _199 = new DataStandardizer.ISO3166.Iso3166Part2("SI-199");
            
            /// <summary>
            /// Makole
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-198")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Makole")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _198 = new DataStandardizer.ISO3166.Iso3166Part2("SI-198");
            
            /// <summary>
            /// Kostanjevica na Krki
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-197")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kostanjevica na Krki")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _197 = new DataStandardizer.ISO3166.Iso3166Part2("SI-197");
            
            /// <summary>
            /// Cirkulane
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-196")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Cirkulane")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _196 = new DataStandardizer.ISO3166.Iso3166Part2("SI-196");
            
            /// <summary>
            /// Apače
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-195")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Apače")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _195 = new DataStandardizer.ISO3166.Iso3166Part2("SI-195");
            
            /// <summary>
            /// Šmartno pri Litiji
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-194")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šmartno pri Litiji")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _194 = new DataStandardizer.ISO3166.Iso3166Part2("SI-194");
            
            /// <summary>
            /// Žužemberk
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-193")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Žužemberk")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _193 = new DataStandardizer.ISO3166.Iso3166Part2("SI-193");
            
            /// <summary>
            /// Žirovnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-192")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Žirovnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _192 = new DataStandardizer.ISO3166.Iso3166Part2("SI-192");
            
            /// <summary>
            /// Žetale
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-191")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Žetale")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _191 = new DataStandardizer.ISO3166.Iso3166Part2("SI-191");
            
            /// <summary>
            /// Žalec
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-190")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Žalec")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _190 = new DataStandardizer.ISO3166.Iso3166Part2("SI-190");
            
            /// <summary>
            /// Vransko
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-189")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Vransko")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _189 = new DataStandardizer.ISO3166.Iso3166Part2("SI-189");
            
            /// <summary>
            /// Brežice
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-009")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Brežice")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _009 = new DataStandardizer.ISO3166.Iso3166Part2("SI-009");
            
            /// <summary>
            /// Izola
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-040")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Izola", SubdivisionNameLocalVariant="Isola")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _040 = new DataStandardizer.ISO3166.Iso3166Part2("SI-040");
            
            /// <summary>
            /// Markovci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-168")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Markovci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _168 = new DataStandardizer.ISO3166.Iso3166Part2("SI-168");
            
            /// <summary>
            /// Cerklje na Gorenjskem
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-012")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Cerklje na Gorenjskem")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _012 = new DataStandardizer.ISO3166.Iso3166Part2("SI-012");
            
            /// <summary>
            /// Destrnik
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-018")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Destrnik")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _018 = new DataStandardizer.ISO3166.Iso3166Part2("SI-018");
            
            /// <summary>
            /// Divača
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-019")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Divača")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _019 = new DataStandardizer.ISO3166.Iso3166Part2("SI-019");
            
            /// <summary>
            /// Dobrepolje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-020")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dobrepolje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _020 = new DataStandardizer.ISO3166.Iso3166Part2("SI-020");
            
            /// <summary>
            /// Zavrč
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-143")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Zavrč")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _143 = new DataStandardizer.ISO3166.Iso3166Part2("SI-143");
            
            /// <summary>
            /// Dobrova-Polhov Gradec
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-021")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dobrova-Polhov Gradec")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _021 = new DataStandardizer.ISO3166.Iso3166Part2("SI-021");
            
            /// <summary>
            /// Odranci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-086")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Odranci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _086 = new DataStandardizer.ISO3166.Iso3166Part2("SI-086");
            
            /// <summary>
            /// Domžale
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-023")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Domžale")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _023 = new DataStandardizer.ISO3166.Iso3166Part2("SI-023");
            
            /// <summary>
            /// Dornava
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-024")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dornava")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _024 = new DataStandardizer.ISO3166.Iso3166Part2("SI-024");
            
            /// <summary>
            /// Zagorje ob Savi
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-142")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Zagorje ob Savi")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _142 = new DataStandardizer.ISO3166.Iso3166Part2("SI-142");
            
            /// <summary>
            /// Dravograd
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-025")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dravograd")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _025 = new DataStandardizer.ISO3166.Iso3166Part2("SI-025");
            
            /// <summary>
            /// Duplek
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-026")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Duplek")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _026 = new DataStandardizer.ISO3166.Iso3166Part2("SI-026");
            
            /// <summary>
            /// Črnomelj
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-017")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Črnomelj")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _017 = new DataStandardizer.ISO3166.Iso3166Part2("SI-017");
            
            /// <summary>
            /// Gorenja vas-Poljane
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-027")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Gorenja vas-Poljane")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _027 = new DataStandardizer.ISO3166.Iso3166Part2("SI-027");
            
            /// <summary>
            /// Gornja Radgona
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-029")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Gornja Radgona")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _029 = new DataStandardizer.ISO3166.Iso3166Part2("SI-029");
            
            /// <summary>
            /// Gornji Grad
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-030")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Gornji Grad")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _030 = new DataStandardizer.ISO3166.Iso3166Part2("SI-030");
            
            /// <summary>
            /// Gornji Petrovci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-031")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Gornji Petrovci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _031 = new DataStandardizer.ISO3166.Iso3166Part2("SI-031");
            
            /// <summary>
            /// Vuzenica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-141")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Vuzenica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _141 = new DataStandardizer.ISO3166.Iso3166Part2("SI-141");
            
            /// <summary>
            /// Grosuplje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-032")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Grosuplje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _032 = new DataStandardizer.ISO3166.Iso3166Part2("SI-032");
            
            /// <summary>
            /// Šalovci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-033")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Šalovci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _033 = new DataStandardizer.ISO3166.Iso3166Part2("SI-033");
            
            /// <summary>
            /// Hrastnik
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-034")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Hrastnik")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _034 = new DataStandardizer.ISO3166.Iso3166Part2("SI-034");
            
            /// <summary>
            /// Hrpelje-Kozina
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-035")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Hrpelje-Kozina")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _035 = new DataStandardizer.ISO3166.Iso3166Part2("SI-035");
            
            /// <summary>
            /// Idrija
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-036")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Idrija")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _036 = new DataStandardizer.ISO3166.Iso3166Part2("SI-036");
            
            /// <summary>
            /// Vrhnika
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-140")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Vrhnika")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _140 = new DataStandardizer.ISO3166.Iso3166Part2("SI-140");
            
            /// <summary>
            /// Ilirska Bistrica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-038")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ilirska Bistrica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _038 = new DataStandardizer.ISO3166.Iso3166Part2("SI-038");
            
            /// <summary>
            /// Gorišnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-028")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Gorišnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _028 = new DataStandardizer.ISO3166.Iso3166Part2("SI-028");
            
            /// <summary>
            /// Tišina
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-010")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Tišina")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _010 = new DataStandardizer.ISO3166.Iso3166Part2("SI-010");
            
            /// <summary>
            /// Črna na Koroškem
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-016")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Črna na Koroškem")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _016 = new DataStandardizer.ISO3166.Iso3166Part2("SI-016");
            
            /// <summary>
            /// Železniki
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-146")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Železniki")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _146 = new DataStandardizer.ISO3166.Iso3166Part2("SI-146");
            
            /// <summary>
            /// Cerknica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-013")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Cerknica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _013 = new DataStandardizer.ISO3166.Iso3166Part2("SI-013");
            
            /// <summary>
            /// Cerkno
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-014")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Cerkno")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _014 = new DataStandardizer.ISO3166.Iso3166Part2("SI-014");
            
            /// <summary>
            /// Črenšovci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-015")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Črenšovci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _015 = new DataStandardizer.ISO3166.Iso3166Part2("SI-015");
            
            /// <summary>
            /// Lovrenc na Pohorju
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-167")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Lovrenc na Pohorju")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _167 = new DataStandardizer.ISO3166.Iso3166Part2("SI-167");
            
            /// <summary>
            /// Križevci
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-166")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Križevci")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _166 = new DataStandardizer.ISO3166.Iso3166Part2("SI-166");
            
            /// <summary>
            /// Kostel
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-165")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Kostel")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _165 = new DataStandardizer.ISO3166.Iso3166Part2("SI-165");
            
            /// <summary>
            /// Komenda
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-164")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Komenda")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _164 = new DataStandardizer.ISO3166.Iso3166Part2("SI-164");
            
            /// <summary>
            /// Jezersko
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-163")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Jezersko")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _163 = new DataStandardizer.ISO3166.Iso3166Part2("SI-163");
            
            /// <summary>
            /// Horjul
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-162")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Horjul")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _162 = new DataStandardizer.ISO3166.Iso3166Part2("SI-162");
            
            /// <summary>
            /// Hodoš
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-161")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Hodoš", SubdivisionNameLocalVariant="Hodos")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _161 = new DataStandardizer.ISO3166.Iso3166Part2("SI-161");
            
            /// <summary>
            /// Hoče-Slivnica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-160")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Hoče-Slivnica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _160 = new DataStandardizer.ISO3166.Iso3166Part2("SI-160");
            
            /// <summary>
            /// Zreče
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-144")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Zreče")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _144 = new DataStandardizer.ISO3166.Iso3166Part2("SI-144");
            
            /// <summary>
            /// Hajdina
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-159")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Hajdina")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _159 = new DataStandardizer.ISO3166.Iso3166Part2("SI-159");
            
            /// <summary>
            /// Dolenjske Toplice
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-157")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dolenjske Toplice")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _157 = new DataStandardizer.ISO3166.Iso3166Part2("SI-157");
            
            /// <summary>
            /// Dobrovnik
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-156")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dobrovnik", SubdivisionNameLocalVariant="Dobronak")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _156 = new DataStandardizer.ISO3166.Iso3166Part2("SI-156");
            
            /// <summary>
            /// Dobrna
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-155")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dobrna")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _155 = new DataStandardizer.ISO3166.Iso3166Part2("SI-155");
            
            /// <summary>
            /// Dobje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-154")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Dobje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _154 = new DataStandardizer.ISO3166.Iso3166Part2("SI-154");
            
            /// <summary>
            /// Cerkvenjak
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-153")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Cerkvenjak")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _153 = new DataStandardizer.ISO3166.Iso3166Part2("SI-153");
            
            /// <summary>
            /// Cankova
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-152")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Cankova")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _152 = new DataStandardizer.ISO3166.Iso3166Part2("SI-152");
            
            /// <summary>
            /// Braslovče
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-151")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Braslovče")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _151 = new DataStandardizer.ISO3166.Iso3166Part2("SI-151");
            
            /// <summary>
            /// Bloke
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-150")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Bloke")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _150 = new DataStandardizer.ISO3166.Iso3166Part2("SI-150");
            
            /// <summary>
            /// Bistrica ob Sotli
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-149")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Bistrica ob Sotli")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _149 = new DataStandardizer.ISO3166.Iso3166Part2("SI-149");
            
            /// <summary>
            /// Benedikt
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-148")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Benedikt")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _148 = new DataStandardizer.ISO3166.Iso3166Part2("SI-148");
            
            /// <summary>
            /// Žiri
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-147")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Žiri")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _147 = new DataStandardizer.ISO3166.Iso3166Part2("SI-147");
            
            /// <summary>
            /// Grad
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-158")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Grad")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _158 = new DataStandardizer.ISO3166.Iso3166Part2("SI-158");
            
            /// <summary>
            /// Ormož
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(423, "SI-087")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 423, "Ormož")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _087 = new DataStandardizer.ISO3166.Iso3166Part2("SI-087");
            #endregion
            
            #region urban municipalities
            /// <summary>
            /// Krško
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-054")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Krško")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _054 = new DataStandardizer.ISO3166.Iso3166Part2("SI-054");
            
            /// <summary>
            /// Kranj
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-052")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Kranj")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _052 = new DataStandardizer.ISO3166.Iso3166Part2("SI-052");
            
            /// <summary>
            /// Koper
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-050")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Koper", SubdivisionNameLocalVariant="Capodistria")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _050 = new DataStandardizer.ISO3166.Iso3166Part2("SI-050");
            
            /// <summary>
            /// Celje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-011")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Celje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _011 = new DataStandardizer.ISO3166.Iso3166Part2("SI-011");
            
            /// <summary>
            /// Novo Mesto
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-085")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Novo Mesto")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _085 = new DataStandardizer.ISO3166.Iso3166Part2("SI-085");
            
            /// <summary>
            /// Maribor
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-070")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Maribor")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _070 = new DataStandardizer.ISO3166.Iso3166Part2("SI-070");
            
            /// <summary>
            /// Slovenj Gradec
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-112")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Slovenj Gradec")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _112 = new DataStandardizer.ISO3166.Iso3166Part2("SI-112");
            
            /// <summary>
            /// Nova Gorica
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-084")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Nova Gorica")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _084 = new DataStandardizer.ISO3166.Iso3166Part2("SI-084");
            
            /// <summary>
            /// Murska Sobota
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-080")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Murska Sobota")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _080 = new DataStandardizer.ISO3166.Iso3166Part2("SI-080");
            
            /// <summary>
            /// Velenje
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-133")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Velenje")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _133 = new DataStandardizer.ISO3166.Iso3166Part2("SI-133");
            
            /// <summary>
            /// Ljubljana
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-061")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Ljubljana")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _061 = new DataStandardizer.ISO3166.Iso3166Part2("SI-061");
            
            /// <summary>
            /// Ptuj
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(497, "SI-096")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("sl", "slv", 497, "Ptuj")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _096 = new DataStandardizer.ISO3166.Iso3166Part2("SI-096");
            #endregion
        }
    }
}

