//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [Iso3166SubdivisionCategoryName("ar", "ara", 349, "muḩāfaz̧ah")]
        [Iso3166SubdivisionCategoryName("en", "eng", 349, "governorate", "governorates")]
        [Iso3166SubdivisionCategoryName("fr", "fra", 349, "gouvernorat")]
        [Iso3166Language("ar", "ara", IsAdministrative=true)]
        [Iso3166Language("en", "eng", IsAdministrative=false)]
        [Iso3166Language("fr", "fra", IsAdministrative=false)]
        public static class PS
        {
            
            #region governorates
            /// <summary>
            /// Qalqilya
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-QQA")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Qalqīlyah", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Qalqilya")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _QQA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-QQA");
            
            /// <summary>
            /// Jenin
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-JEN")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Janīn", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Jenin")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _JEN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-JEN");
            
            /// <summary>
            /// Ramallah
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-RBH")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Rām Allāh wal Bīrah", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Ramallah")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _RBH = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-RBH");
            
            /// <summary>
            /// Rafah
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-RFH")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Rafaḩ", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Rafah")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _RFH = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-RFH");
            
            /// <summary>
            /// Salfit
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-SLT")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Salfīt", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Salfit")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SLT = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-SLT");
            
            /// <summary>
            /// Tubas
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-TBS")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Ţūbās", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Tubas")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _TBS = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-TBS");
            
            /// <summary>
            /// Nablus
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-NBS")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Nāblus", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Nablus")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _NBS = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-NBS");
            
            /// <summary>
            /// Khan Yunis
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-KYS")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Khān Yūnis", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Khan Yunis")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _KYS = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-KYS");
            
            /// <summary>
            /// Jericho and Al Aghwar
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-JRH")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Arīḩā wal Aghwār", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Jericho and Al Aghwar")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _JRH = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-JRH");
            
            /// <summary>
            /// North Gaza
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-NGZ")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Shamāl Ghazzah", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "North Gaza")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _NGZ = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-NGZ");
            
            /// <summary>
            /// Jerusalem
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-JEM")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Al Quds", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Jerusalem")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _JEM = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-JEM");
            
            /// <summary>
            /// Tulkarm
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-TKM")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Ţūlkarm", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Tulkarm")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _TKM = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-TKM");
            
            /// <summary>
            /// Gaza
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-GZA")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Ghazzah", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Gaza")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _GZA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-GZA");
            
            /// <summary>
            /// Deir El Balah
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-DEB")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Dayr al Balaḩ", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Deir El Balah")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _DEB = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-DEB");
            
            /// <summary>
            /// Bethlehem
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-BTH")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Bayt Laḩm", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Bethlehem")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _BTH = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-BTH");
            
            /// <summary>
            /// Hebron
            /// </summary>
            [Iso3166SubdivisionCode(349, "PS-HBN")]
            [Iso3166SubdivisionName("ar", "ara", 349, "Al Khalīl", RomanizationSystem="BGN/PCGN 1956")]
            [Iso3166SubdivisionName("en", "eng", 349, "Hebron")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HBN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("PS-HBN");
            #endregion
        }
    }
}