//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    
    
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2
    {
        
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 295, "department", "departments")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 295, "département")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("es", "spa", 295, "departamento")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 350, "capital", "capitals")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 350, "capitale")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("es", "spa", 350, "capital")]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("gn", "grn", IsAdministrative=true)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("es", "spa", IsAdministrative=true)]
        public static class PY
        {
            
            #region departments
            /// <summary>
            /// Itapúa
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-7")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Itapúa")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _7 = new DataStandardizer.ISO3166.Iso3166Part2("PY-7");
            
            /// <summary>
            /// Caaguazú
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-5")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Caaguazú")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _5 = new DataStandardizer.ISO3166.Iso3166Part2("PY-5");
            
            /// <summary>
            /// Caazapá
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-6")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Caazapá")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _6 = new DataStandardizer.ISO3166.Iso3166Part2("PY-6");
            
            /// <summary>
            /// Guairá
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-4")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Guairá")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _4 = new DataStandardizer.ISO3166.Iso3166Part2("PY-4");
            
            /// <summary>
            /// Boquerón
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-19")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Boquerón")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _19 = new DataStandardizer.ISO3166.Iso3166Part2("PY-19");
            
            /// <summary>
            /// San Pedro
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-2")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "San Pedro")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _2 = new DataStandardizer.ISO3166.Iso3166Part2("PY-2");
            
            /// <summary>
            /// Concepción
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-1")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Concepción")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _1 = new DataStandardizer.ISO3166.Iso3166Part2("PY-1");
            
            /// <summary>
            /// Cordillera
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-3")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Cordillera")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _3 = new DataStandardizer.ISO3166.Iso3166Part2("PY-3");
            
            /// <summary>
            /// Misiones
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-8")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Misiones")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _8 = new DataStandardizer.ISO3166.Iso3166Part2("PY-8");
            
            /// <summary>
            /// Alto Paraná
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-10")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Alto Paraná")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _10 = new DataStandardizer.ISO3166.Iso3166Part2("PY-10");
            
            /// <summary>
            /// Central
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-11")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Central")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _11 = new DataStandardizer.ISO3166.Iso3166Part2("PY-11");
            
            /// <summary>
            /// Paraguarí
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-9")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Paraguarí")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _9 = new DataStandardizer.ISO3166.Iso3166Part2("PY-9");
            
            /// <summary>
            /// Amambay
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-13")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Amambay")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _13 = new DataStandardizer.ISO3166.Iso3166Part2("PY-13");
            
            /// <summary>
            /// Canindeyú
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-14")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Canindeyú")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _14 = new DataStandardizer.ISO3166.Iso3166Part2("PY-14");
            
            /// <summary>
            /// Presidente Hayes
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-15")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Presidente Hayes")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _15 = new DataStandardizer.ISO3166.Iso3166Part2("PY-15");
            
            /// <summary>
            /// Alto Paraguay
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-16")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Alto Paraguay")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _16 = new DataStandardizer.ISO3166.Iso3166Part2("PY-16");
            
            /// <summary>
            /// Ñeembucú
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(295, "PY-12")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 295, "Ñeembucú")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _12 = new DataStandardizer.ISO3166.Iso3166Part2("PY-12");
            #endregion
            
            #region capitals
            /// <summary>
            /// Asunción
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(350, "PY-ASU")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 350, "Asunción")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _ASU = new DataStandardizer.ISO3166.Iso3166Part2("PY-ASU");
            #endregion
        }
    }
}

