//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    
    
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2
    {
        
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 272, "special municipality", "special municipalities")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 272, "commune speciale")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("nl", "nld", 272, "bijzondere gemeente")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute(null, "pap", 272, "munisipio spesial")]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=true)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("nl", "nld", IsAdministrative=true)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute(null, "pap", IsAdministrative=true)]
        public static class BQ
        {
            
            #region special municipalities
            /// <summary>
            /// Saba
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(272, "BQ-SA")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("en", "eng", 272, "Saba")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("nl", "nld", 272, "Saba")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute(null, "pap", 272, "Saba")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SA = new DataStandardizer.ISO3166.Iso3166Part2("BQ-SA");
            
            /// <summary>
            /// Sint Eustatius
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(272, "BQ-SE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("en", "eng", 272, "Sint Eustatius")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("nl", "nld", 272, "Sint Eustatius")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute(null, "pap", 272, "Sint Eustatius")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SE = new DataStandardizer.ISO3166.Iso3166Part2("BQ-SE");
            
            /// <summary>
            /// Bonaire
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(272, "BQ-BO")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("en", "eng", 272, "Bonaire")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("nl", "nld", 272, "Bonaire")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute(null, "pap", 272, "Boneiru")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _BO = new DataStandardizer.ISO3166.Iso3166Part2("BQ-BO");
            #endregion
        }
    }
}

