//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    
    
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2
    {
        
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 204, "county", "counties")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 204, "comitat")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("hu", "hun", 204, "megye")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 245, "city with county rights", "cities of county right")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 245, "ville ayant un rang de comitat")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("hu", "hun", 245, "megyei jogú város")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 406, "capital city", "capital cities")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 406, "ville capitale")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("hu", "hun", 406, "főváros")]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("hu", "hun", IsAdministrative=true)]
        public static class HU
        {
            
            #region counties
            /// <summary>
            /// Csongrád-Csanád
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-CS")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Csongrád-Csanád")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _CS = new DataStandardizer.ISO3166.Iso3166Part2("HU-CS");
            
            /// <summary>
            /// Fejér
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-FE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Fejér")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _FE = new DataStandardizer.ISO3166.Iso3166Part2("HU-FE");
            
            /// <summary>
            /// Győr-Moson-Sopron
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-GS")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Győr-Moson-Sopron")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _GS = new DataStandardizer.ISO3166.Iso3166Part2("HU-GS");
            
            /// <summary>
            /// Hajdú-Bihar
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-HB")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Hajdú-Bihar")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _HB = new DataStandardizer.ISO3166.Iso3166Part2("HU-HB");
            
            /// <summary>
            /// Heves
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-HE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Heves")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _HE = new DataStandardizer.ISO3166.Iso3166Part2("HU-HE");
            
            /// <summary>
            /// Nógrád
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-NO")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Nógrád")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _NO = new DataStandardizer.ISO3166.Iso3166Part2("HU-NO");
            
            /// <summary>
            /// Zala
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-ZA")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Zala")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _ZA = new DataStandardizer.ISO3166.Iso3166Part2("HU-ZA");
            
            /// <summary>
            /// Tolna
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-TO")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Tolna")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _TO = new DataStandardizer.ISO3166.Iso3166Part2("HU-TO");
            
            /// <summary>
            /// Borsod-Abaúj-Zemplén
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-BZ")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Borsod-Abaúj-Zemplén")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _BZ = new DataStandardizer.ISO3166.Iso3166Part2("HU-BZ");
            
            /// <summary>
            /// Bács-Kiskun
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-BK")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Bács-Kiskun")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _BK = new DataStandardizer.ISO3166.Iso3166Part2("HU-BK");
            
            /// <summary>
            /// Jász-Nagykun-Szolnok
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-JN")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Jász-Nagykun-Szolnok")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _JN = new DataStandardizer.ISO3166.Iso3166Part2("HU-JN");
            
            /// <summary>
            /// Békés
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-BE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Békés")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _BE = new DataStandardizer.ISO3166.Iso3166Part2("HU-BE");
            
            /// <summary>
            /// Komárom-Esztergom
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-KE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Komárom-Esztergom")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _KE = new DataStandardizer.ISO3166.Iso3166Part2("HU-KE");
            
            /// <summary>
            /// Baranya
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-BA")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Baranya")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _BA = new DataStandardizer.ISO3166.Iso3166Part2("HU-BA");
            
            /// <summary>
            /// Veszprém
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-VE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Veszprém")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _VE = new DataStandardizer.ISO3166.Iso3166Part2("HU-VE");
            
            /// <summary>
            /// Vas
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-VA")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Vas")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _VA = new DataStandardizer.ISO3166.Iso3166Part2("HU-VA");
            
            /// <summary>
            /// Pest
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-PE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Pest")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _PE = new DataStandardizer.ISO3166.Iso3166Part2("HU-PE");
            
            /// <summary>
            /// Szabolcs-Szatmár-Bereg
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-SZ")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Szabolcs-Szatmár-Bereg")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SZ = new DataStandardizer.ISO3166.Iso3166Part2("HU-SZ");
            
            /// <summary>
            /// Somogy
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(204, "HU-SO")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 204, "Somogy")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SO = new DataStandardizer.ISO3166.Iso3166Part2("HU-SO");
            #endregion
            
            #region cities of county right
            /// <summary>
            /// Debrecen
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-DE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Debrecen")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _DE = new DataStandardizer.ISO3166.Iso3166Part2("HU-DE");
            
            /// <summary>
            /// Győr
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-GY")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Győr")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _GY = new DataStandardizer.ISO3166.Iso3166Part2("HU-GY");
            
            /// <summary>
            /// Érd
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-ER")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Érd")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _ER = new DataStandardizer.ISO3166.Iso3166Part2("HU-ER");
            
            /// <summary>
            /// Eger
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-EG")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Eger")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _EG = new DataStandardizer.ISO3166.Iso3166Part2("HU-EG");
            
            /// <summary>
            /// Dunaújváros
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-DU")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Dunaújváros")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _DU = new DataStandardizer.ISO3166.Iso3166Part2("HU-DU");
            
            /// <summary>
            /// Hódmezővásárhely
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-HV")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Hódmezővásárhely")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _HV = new DataStandardizer.ISO3166.Iso3166Part2("HU-HV");
            
            /// <summary>
            /// Zalaegerszeg
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-ZE")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Zalaegerszeg")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _ZE = new DataStandardizer.ISO3166.Iso3166Part2("HU-ZE");
            
            /// <summary>
            /// Szombathely
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-SH")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Szombathely")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SH = new DataStandardizer.ISO3166.Iso3166Part2("HU-SH");
            
            /// <summary>
            /// Nagykanizsa
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-NK")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Nagykanizsa")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _NK = new DataStandardizer.ISO3166.Iso3166Part2("HU-NK");
            
            /// <summary>
            /// Nyíregyháza
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-NY")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Nyíregyháza")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _NY = new DataStandardizer.ISO3166.Iso3166Part2("HU-NY");
            
            /// <summary>
            /// Pécs
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-PS")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Pécs")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _PS = new DataStandardizer.ISO3166.Iso3166Part2("HU-PS");
            
            /// <summary>
            /// Szeged
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-SD")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Szeged")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SD = new DataStandardizer.ISO3166.Iso3166Part2("HU-SD");
            
            /// <summary>
            /// Székesfehérvár
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-SF")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Székesfehérvár")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SF = new DataStandardizer.ISO3166.Iso3166Part2("HU-SF");
            
            /// <summary>
            /// Békéscsaba
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-BC")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Békéscsaba")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _BC = new DataStandardizer.ISO3166.Iso3166Part2("HU-BC");
            
            /// <summary>
            /// Miskolc
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-MI")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Miskolc")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _MI = new DataStandardizer.ISO3166.Iso3166Part2("HU-MI");
            
            /// <summary>
            /// Kaposvár
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-KV")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Kaposvár")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _KV = new DataStandardizer.ISO3166.Iso3166Part2("HU-KV");
            
            /// <summary>
            /// Sopron
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-SN")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Sopron")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SN = new DataStandardizer.ISO3166.Iso3166Part2("HU-SN");
            
            /// <summary>
            /// Szekszárd
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-SS")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Szekszárd")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SS = new DataStandardizer.ISO3166.Iso3166Part2("HU-SS");
            
            /// <summary>
            /// Kecskemét
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-KM")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Kecskemét")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _KM = new DataStandardizer.ISO3166.Iso3166Part2("HU-KM");
            
            /// <summary>
            /// Salgótarján
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-ST")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Salgótarján")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _ST = new DataStandardizer.ISO3166.Iso3166Part2("HU-ST");
            
            /// <summary>
            /// Tatabánya
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-TB")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Tatabánya")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _TB = new DataStandardizer.ISO3166.Iso3166Part2("HU-TB");
            
            /// <summary>
            /// Veszprém
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-VM")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Veszprém")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _VM = new DataStandardizer.ISO3166.Iso3166Part2("HU-VM");
            
            /// <summary>
            /// Szolnok
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(245, "HU-SK")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 245, "Szolnok")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SK = new DataStandardizer.ISO3166.Iso3166Part2("HU-SK");
            #endregion
            
            #region capital cities
            /// <summary>
            /// Budapest
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(406, "HU-BU")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("hu", "hun", 406, "Budapest")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _BU = new DataStandardizer.ISO3166.Iso3166Part2("HU-BU");
            #endregion
        }
    }
}

