//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    
    
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2
    {
        
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 464, "administrative precinct", "administrative precincts")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 464, "circonscription")]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=true)]
        public static class WF
        {
            
            #region administrative precincts
            /// <summary>
            /// Uvea
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(464, "WF-UV")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("fr", "fra", 464, "Uvea")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _UV = new DataStandardizer.ISO3166.Iso3166Part2("WF-UV");
            
            /// <summary>
            /// Alo
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(464, "WF-AL")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("fr", "fra", 464, "Alo")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _AL = new DataStandardizer.ISO3166.Iso3166Part2("WF-AL");
            
            /// <summary>
            /// Sigave
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(464, "WF-SG")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("fr", "fra", 464, "Sigave")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _SG = new DataStandardizer.ISO3166.Iso3166Part2("WF-SG");
            #endregion
        }
    }
}

