//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [Iso3166SubdivisionCategoryName("en", "eng", 419, "region", "regions")]
        [Iso3166SubdivisionCategoryName("fr", "fra", 419, "région")]
        [Iso3166SubdivisionCategoryName("is", "isl", 419, "landsvæði")]
        [Iso3166SubdivisionCategoryName("en", "eng", 485, "municipality", "municipalities")]
        [Iso3166SubdivisionCategoryName("fr", "fra", 485, "municipalité")]
        [Iso3166SubdivisionCategoryName("is", "isl", 485, "sveitarfélagið")]
        [Iso3166Language("en", "eng", IsAdministrative=false)]
        [Iso3166Language("fr", "fra", IsAdministrative=false)]
        [Iso3166Language("is", "isl", IsAdministrative=true)]
        public static class IS
        {
            
            #region regions
            /// <summary>
            /// Höfuðborgarsvæði
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 419, "Höfuðborgarsvæði")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _1 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-1");
            
            /// <summary>
            /// Suðurnes
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-2")]
            [Iso3166SubdivisionName("is", "isl", 419, "Suðurnes")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _2 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-2");
            
            /// <summary>
            /// Vesturland
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 419, "Vesturland")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _3 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-3");
            
            /// <summary>
            /// Vestfirðir
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 419, "Vestfirðir")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _4 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-4");
            
            /// <summary>
            /// Norðurland vestra
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-5")]
            [Iso3166SubdivisionName("is", "isl", 419, "Norðurland vestra")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _5 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-5");
            
            /// <summary>
            /// Norðurland eystra
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 419, "Norðurland eystra")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _6 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-6");
            
            /// <summary>
            /// Austurland
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-7")]
            [Iso3166SubdivisionName("is", "isl", 419, "Austurland")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _7 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-7");
            
            /// <summary>
            /// Suðurland
            /// </summary>
            [Iso3166SubdivisionCode(419, "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 419, "Suðurland")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _8 = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-8");
            #endregion
            
            #region municipalities
            /// <summary>
            /// Stykkishólmsbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-STY", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Stykkishólmsbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _STY = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-STY");
            
            /// <summary>
            /// Árneshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-ARN", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Árneshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _ARN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-ARN");
            
            /// <summary>
            /// Snæfellsbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SNF", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Snæfellsbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SNF = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SNF");
            
            /// <summary>
            /// Skorradalshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SKO", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Skorradalshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SKO = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SKO");
            
            /// <summary>
            /// Hvalfjarðarsveit
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-HVA", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Hvalfjarðarsveit")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HVA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-HVA");
            
            /// <summary>
            /// Grundarfjarðarbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-GRU", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Grundarfjarðarbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _GRU = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-GRU");
            
            /// <summary>
            /// Eyja- og Miklaholtshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-EOM", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Eyja- og Miklaholtshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _EOM = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-EOM");
            
            /// <summary>
            /// Garðabær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-GAR", "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 485, "Garðabær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _GAR = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-GAR");
            
            /// <summary>
            /// Dalabyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-DAB", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Dalabyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _DAB = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-DAB");
            
            /// <summary>
            /// Borgarbyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-BOG", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Borgarbyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _BOG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-BOG");
            
            /// <summary>
            /// Reykjanesbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-RKN", "IS-2")]
            [Iso3166SubdivisionName("is", "isl", 485, "Reykjanesbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _RKN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-RKN");
            
            /// <summary>
            /// Sveitarfélagið Vogar
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SVG", "IS-2")]
            [Iso3166SubdivisionName("is", "isl", 485, "Sveitarfélagið Vogar")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SVG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SVG");
            
            /// <summary>
            /// Suðurnesjabær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SDN", "IS-2")]
            [Iso3166SubdivisionName("is", "isl", 485, "Suðurnesjabær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SDN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SDN");
            
            /// <summary>
            /// Kjósarhreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-KJO", "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 485, "Kjósarhreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _KJO = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-KJO");
            
            /// <summary>
            /// Grindavíkurbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-GRN", "IS-2")]
            [Iso3166SubdivisionName("is", "isl", 485, "Grindavíkurbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _GRN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-GRN");
            
            /// <summary>
            /// Seltjarnarnesbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SEL", "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 485, "Seltjarnarnesbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SEL = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SEL");
            
            /// <summary>
            /// Reykjavíkurborg
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-RKV", "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 485, "Reykjavíkurborg")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _RKV = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-RKV");
            
            /// <summary>
            /// Hafnarfjarðarkaupstaður
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-HAF", "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 485, "Hafnarfjarðarkaupstaður")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HAF = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-HAF");
            
            /// <summary>
            /// Bolungarvíkurkaupstaður
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-BOL", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Bolungarvíkurkaupstaður")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _BOL = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-BOL");
            
            /// <summary>
            /// Mosfellsbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-MOS", "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 485, "Mosfellsbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _MOS = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-MOS");
            
            /// <summary>
            /// Kópavogsbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-KOP", "IS-1")]
            [Iso3166SubdivisionName("is", "isl", 485, "Kópavogsbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _KOP = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-KOP");
            
            /// <summary>
            /// Akraneskaupstaður
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-AKN", "IS-3")]
            [Iso3166SubdivisionName("is", "isl", 485, "Akraneskaupstaður")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _AKN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-AKN");
            
            /// <summary>
            /// Ísafjarðarbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-ISA", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Ísafjarðarbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _ISA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-ISA");
            
            /// <summary>
            /// Múlaþing
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-MUL", "IS-7")]
            [Iso3166SubdivisionName("is", "isl", 485, "Múlaþing")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _MUL = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-MUL");
            
            /// <summary>
            /// Reykhólahreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-RHH", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Reykhólahreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _RHH = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-RHH");
            
            /// <summary>
            /// Norðurþing
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-NOR", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Norðurþing")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _NOR = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-NOR");
            
            /// <summary>
            /// Svalbarðsstrandarhreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SBT", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Svalbarðsstrandarhreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SBT = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SBT");
            
            /// <summary>
            /// Þingeyjarsveit
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-THG", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Þingeyjarsveit")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _THG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-THG");
            
            /// <summary>
            /// Tjörneshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-TJO", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Tjörneshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _TJO = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-TJO");
            
            /// <summary>
            /// Fjarðabyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-FJD", "IS-7")]
            [Iso3166SubdivisionName("is", "isl", 485, "Fjarðabyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _FJD = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-FJD");
            
            /// <summary>
            /// Fljótsdalshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-FLR", "IS-7")]
            [Iso3166SubdivisionName("is", "isl", 485, "Fljótsdalshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _FLR = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-FLR");
            
            /// <summary>
            /// Sveitarfélagið Hornafjörður
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SHF", "IS-7")]
            [Iso3166SubdivisionName("is", "isl", 485, "Sveitarfélagið Hornafjörður")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SHF = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SHF");
            
            /// <summary>
            /// Kaldrananeshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-KAL", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Kaldrananeshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _KAL = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-KAL");
            
            /// <summary>
            /// Ásahreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-ASA", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Ásahreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _ASA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-ASA");
            
            /// <summary>
            /// Bláskógabyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-BLA", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Bláskógabyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _BLA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-BLA");
            
            /// <summary>
            /// Langanesbyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-LAN", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Langanesbyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _LAN = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-LAN");
            
            /// <summary>
            /// Flóahreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-FLA", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Flóahreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _FLA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-FLA");
            
            /// <summary>
            /// Hrunamannahreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-HRU", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Hrunamannahreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HRU = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-HRU");
            
            /// <summary>
            /// Hveragerðisbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-HVE", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Hveragerðisbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HVE = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-HVE");
            
            /// <summary>
            /// Mýrdalshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-MYR", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Mýrdalshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _MYR = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-MYR");
            
            /// <summary>
            /// Rangárþing eystra
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-RGE", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Rangárþing eystra")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _RGE = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-RGE");
            
            /// <summary>
            /// Rangárþing ytra
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-RGY", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Rangárþing ytra")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _RGY = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-RGY");
            
            /// <summary>
            /// Sveitarfélagið Árborg
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SFA", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Sveitarfélagið Árborg")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SFA = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SFA");
            
            /// <summary>
            /// Skaftárhreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SKF", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Skaftárhreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SKF = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SKF");
            
            /// <summary>
            /// Skeiða- og Gnúpverjahreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SOG", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Skeiða- og Gnúpverjahreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SOG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SOG");
            
            /// <summary>
            /// Sveitarfélagið Ölfus
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SOL", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Sveitarfélagið Ölfus")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SOL = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SOL");
            
            /// <summary>
            /// Vestmannaeyjabær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-VEM", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Vestmannaeyjabær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _VEM = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-VEM");
            
            /// <summary>
            /// Grímsnes- og Grafningshreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-GOG", "IS-8")]
            [Iso3166SubdivisionName("is", "isl", 485, "Grímsnes- og Grafningshreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _GOG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-GOG");
            
            /// <summary>
            /// Hörgársveit
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-HRG", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Hörgársveit")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HRG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-HRG");
            
            /// <summary>
            /// Vopnafjarðarhreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-VOP", "IS-7")]
            [Iso3166SubdivisionName("is", "isl", 485, "Vopnafjarðarhreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _VOP = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-VOP");
            
            /// <summary>
            /// Vesturbyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-VER", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Vesturbyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _VER = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-VER");
            
            /// <summary>
            /// Súðavíkurhreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SDV", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Súðavíkurhreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SDV = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SDV");
            
            /// <summary>
            /// Strandabyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-STR", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Strandabyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _STR = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-STR");
            
            /// <summary>
            /// Grýtubakkahreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-GRY", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Grýtubakkahreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _GRY = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-GRY");
            
            /// <summary>
            /// Tálknafjarðarhreppur
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-TAL", "IS-4")]
            [Iso3166SubdivisionName("is", "isl", 485, "Tálknafjarðarhreppur")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _TAL = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-TAL");
            
            /// <summary>
            /// Húnabyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-HUG", "IS-5")]
            [Iso3166SubdivisionName("is", "isl", 485, "Húnabyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HUG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-HUG");
            
            /// <summary>
            /// Skagabyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SKG", "IS-5")]
            [Iso3166SubdivisionName("is", "isl", 485, "Skagabyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SKG = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SKG");
            
            /// <summary>
            /// Skagafjörður
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SKR", "IS-5")]
            [Iso3166SubdivisionName("is", "isl", 485, "Skagafjörður")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SKR = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SKR");
            
            /// <summary>
            /// Sveitarfélagið Skagaströnd
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-SSS", "IS-5")]
            [Iso3166SubdivisionName("is", "isl", 485, "Sveitarfélagið Skagaströnd")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _SSS = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-SSS");
            
            /// <summary>
            /// Húnaþing vestra
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-HUV", "IS-5")]
            [Iso3166SubdivisionName("is", "isl", 485, "Húnaþing vestra")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _HUV = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-HUV");
            
            /// <summary>
            /// Akureyrarbær
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-AKU", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Akureyrarbær")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _AKU = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-AKU");
            
            /// <summary>
            /// Fjallabyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-FJL", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Fjallabyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _FJL = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-FJL");
            
            /// <summary>
            /// Dalvíkurbyggð
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-DAV", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Dalvíkurbyggð")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _DAV = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-DAV");
            
            /// <summary>
            /// Eyjafjarðarsveit
            /// </summary>
            [Iso3166SubdivisionCode(485, "IS-EYF", "IS-6")]
            [Iso3166SubdivisionName("is", "isl", 485, "Eyjafjarðarsveit")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _EYF = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("IS-EYF");
            #endregion
        }
    }
}