//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [Iso3166SubdivisionCategoryName("en", "eng", 292, "city", "cities")]
        [Iso3166SubdivisionCategoryName("fr", "fra", 292, "ville")]
        [Iso3166SubdivisionCategoryName("tk", "tuk", 292, "şäher")]
        [Iso3166SubdivisionCategoryName("en", "eng", 425, "region", "regions")]
        [Iso3166SubdivisionCategoryName("fr", "fra", 425, "région")]
        [Iso3166SubdivisionCategoryName("tk", "tuk", 425, "welaýat")]
        [Iso3166Language("en", "eng", IsAdministrative=false)]
        [Iso3166Language("fr", "fra", IsAdministrative=false)]
        [Iso3166Language("tk", "tuk", IsAdministrative=true)]
        public static class TM
        {
            
            #region cities
            /// <summary>
            /// Aşgabat
            /// </summary>
            [Iso3166SubdivisionCode(292, "TM-S")]
            [Iso3166SubdivisionName("tk", "tuk", 292, "Aşgabat")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _S = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("TM-S");
            #endregion
            
            #region regions
            /// <summary>
            /// Ahal
            /// </summary>
            [Iso3166SubdivisionCode(425, "TM-A")]
            [Iso3166SubdivisionName("tk", "tuk", 425, "Ahal")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _A = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("TM-A");
            
            /// <summary>
            /// Balkan
            /// </summary>
            [Iso3166SubdivisionCode(425, "TM-B")]
            [Iso3166SubdivisionName("tk", "tuk", 425, "Balkan")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _B = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("TM-B");
            
            /// <summary>
            /// Daşoguz
            /// </summary>
            [Iso3166SubdivisionCode(425, "TM-D")]
            [Iso3166SubdivisionName("tk", "tuk", 425, "Daşoguz")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _D = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("TM-D");
            
            /// <summary>
            /// Lebap
            /// </summary>
            [Iso3166SubdivisionCode(425, "TM-L")]
            [Iso3166SubdivisionName("tk", "tuk", 425, "Lebap")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _L = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("TM-L");
            
            /// <summary>
            /// Mary
            /// </summary>
            [Iso3166SubdivisionCode(425, "TM-M")]
            [Iso3166SubdivisionName("tk", "tuk", 425, "Mary")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2Subdivision _M = new DataStandardizer.ISO3166.Iso3166Part2Subdivision("TM-M");
            #endregion
        }
    }
}