//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    
    
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2
    {
        
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("de", "deu", 392, "Bundesland")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 392, "state", "states")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 392, "État")]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("de", "deu", IsAdministrative=true)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        public static class AT
        {
            
            #region states
            /// <summary>
            /// Oberösterreich
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-4")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Oberösterreich")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _4 = new DataStandardizer.ISO3166.Iso3166Part2("AT-4");
            
            /// <summary>
            /// Kärnten
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-2")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Kärnten")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _2 = new DataStandardizer.ISO3166.Iso3166Part2("AT-2");
            
            /// <summary>
            /// Niederösterreich
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-3")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Niederösterreich")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _3 = new DataStandardizer.ISO3166.Iso3166Part2("AT-3");
            
            /// <summary>
            /// Burgenland
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-1")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Burgenland")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _1 = new DataStandardizer.ISO3166.Iso3166Part2("AT-1");
            
            /// <summary>
            /// Wien
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-9")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Wien")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _9 = new DataStandardizer.ISO3166.Iso3166Part2("AT-9");
            
            /// <summary>
            /// Vorarlberg
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-8")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Vorarlberg")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _8 = new DataStandardizer.ISO3166.Iso3166Part2("AT-8");
            
            /// <summary>
            /// Tirol
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-7")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Tirol")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _7 = new DataStandardizer.ISO3166.Iso3166Part2("AT-7");
            
            /// <summary>
            /// Steiermark
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-6")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Steiermark")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _6 = new DataStandardizer.ISO3166.Iso3166Part2("AT-6");
            
            /// <summary>
            /// Salzburg
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(392, "AT-5")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("de", "deu", 392, "Salzburg")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _5 = new DataStandardizer.ISO3166.Iso3166Part2("AT-5");
            #endregion
        }
    }
}

