//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.ISO3166
{
    
    
    /// <summary>
    /// Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2
    {
        
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 365, "province", "provinces")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 365, "province")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("es", "spa", 365, "provincia")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 441, "special municipality", "special municipalities")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 441, "municipalité spéciale")]
        [DataStandardizer.ISO3166.Iso3166SubdivisionCategoryNameAttribute("es", "spa", 441, "municipio especial")]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.ISO3166.Iso3166LanguageAttribute("es", "spa", IsAdministrative=true)]
        public static class CU
        {
            
            #region provinces
            /// <summary>
            /// Villa Clara
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-05")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Villa Clara")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _05 = new DataStandardizer.ISO3166.Iso3166Part2("CU-05");
            
            /// <summary>
            /// Holguín
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-11")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Holguín")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _11 = new DataStandardizer.ISO3166.Iso3166Part2("CU-11");
            
            /// <summary>
            /// Granma
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-12")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Granma")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _12 = new DataStandardizer.ISO3166.Iso3166Part2("CU-12");
            
            /// <summary>
            /// Matanzas
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-04")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Matanzas")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _04 = new DataStandardizer.ISO3166.Iso3166Part2("CU-04");
            
            /// <summary>
            /// Santiago de Cuba
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-13")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Santiago de Cuba")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _13 = new DataStandardizer.ISO3166.Iso3166Part2("CU-13");
            
            /// <summary>
            /// Artemisa
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-15")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Artemisa")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _15 = new DataStandardizer.ISO3166.Iso3166Part2("CU-15");
            
            /// <summary>
            /// Mayabeque
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-16")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Mayabeque")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _16 = new DataStandardizer.ISO3166.Iso3166Part2("CU-16");
            
            /// <summary>
            /// Las Tunas
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-10")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Las Tunas")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _10 = new DataStandardizer.ISO3166.Iso3166Part2("CU-10");
            
            /// <summary>
            /// Camagüey
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-09")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Camagüey")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _09 = new DataStandardizer.ISO3166.Iso3166Part2("CU-09");
            
            /// <summary>
            /// Guantánamo
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-14")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Guantánamo")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _14 = new DataStandardizer.ISO3166.Iso3166Part2("CU-14");
            
            /// <summary>
            /// Sancti Spíritus
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-07")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Sancti Spíritus")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _07 = new DataStandardizer.ISO3166.Iso3166Part2("CU-07");
            
            /// <summary>
            /// Cienfuegos
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-06")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Cienfuegos")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _06 = new DataStandardizer.ISO3166.Iso3166Part2("CU-06");
            
            /// <summary>
            /// Pinar del Río
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-01")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Pinar del Río")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _01 = new DataStandardizer.ISO3166.Iso3166Part2("CU-01");
            
            /// <summary>
            /// La Habana
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-03")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "La Habana")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _03 = new DataStandardizer.ISO3166.Iso3166Part2("CU-03");
            
            /// <summary>
            /// Ciego de Ávila
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(365, "CU-08")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 365, "Ciego de Ávila")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _08 = new DataStandardizer.ISO3166.Iso3166Part2("CU-08");
            #endregion
            
            #region special municipalities
            /// <summary>
            /// Isla de la Juventud
            /// </summary>
            [DataStandardizer.ISO3166.Iso3166SubdivisionCodeAttribute(441, "CU-99")]
            [DataStandardizer.ISO3166.Iso3166SubdivisionNameAttribute("es", "spa", 441, "Isla de la Juventud")]
            public static readonly DataStandardizer.ISO3166.Iso3166Part2 _99 = new DataStandardizer.ISO3166.Iso3166Part2("CU-99");
            #endregion
        }
    }
}

