//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.Geography
{
    
    
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("af", "afr", 428, "provinsie")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 428, "province", "provinces")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 428, "province")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("nr", "nbl", 428, "iProvinsi")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute(null, "nso", 428, "profense")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("st", "sot", 428, "provense")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("ss", "ssw", 428, "fundzeni")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("tn", "tsn", 428, "porofense")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("ts", "tso", 428, "fundzankulu")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("ve", "ven", 428, "vundu")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("xh", "xho", 428, "phondo")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("zu", "zul", 428, "fundazwe")]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("af", "afr", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("en", "eng", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("nr", "nbl", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute(null, "nso", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("st", "sot", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("ss", "ssw", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("tn", "tsn", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("ts", "tso", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("ve", "ven", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("xh", "xho", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("zu", "zul", IsAdministrative=true)]
        public static class ZA
        {
            
            #region provinces
            /// <summary>
            /// Northern Cape
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-NC")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Noord-Kaap")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Northern Cape")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iTlhagwini-Kapa")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Kapa Leboya")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Kapa Leboya")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Kapa Bokone", SubdivisionNameLocalVariant="Kapa Leboa")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Kapa-N\'walungu")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "Kapa Devhula")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Mntla-Koloni")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Nyakatho-Kapa", SubdivisionNameLocalVariant="Nyakatho-Koloni")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _NC = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-NC");
            
            /// <summary>
            /// Mpumalanga
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-MP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iMpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ss", "ssw", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Mpumalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Mpumalanga")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MP = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-MP");
            
            /// <summary>
            /// Eastern Cape
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-EC")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Oos-Kaap")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Eastern Cape")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iPumalanga-Kapa")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Kapa Bohlabela")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Kapa Botjhabela")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Kapa Botlhaba")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Kapa-Vuxa")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "Kapa Vhubvaḓuvha")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Mpuma-Koloni")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Mpumalanga-Kapa", SubdivisionNameLocalVariant="Mpumalanga-Koloni")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _EC = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-EC");
            
            /// <summary>
            /// Gauteng
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-GP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Gauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Gauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iGauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Gauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Kgauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ss", "ssw", 428, "Gauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Gauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Gauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "Gauteng")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Rhawuti")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Gauteng")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _GP = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-GP");
            
            /// <summary>
            /// North-West
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-NW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Noordwes")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "North-West")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iTlhagwini-Tjhingalanga")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Lebowa Bodikela")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Leboya (le) Bophirima")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Bokone Bophirima")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "N\'walungu-Vupeladyambu")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Mntla-Ntshona")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Nyakatho-Ntshonalanga")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _NW = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-NW");
            
            /// <summary>
            /// Limpopo
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-LP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ss", "ssw", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "Vhembe")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Limpopo")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Limpopo")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _LP = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-LP");
            
            /// <summary>
            /// Kwazulu-Natal
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-KZN")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "KwaZulu-Natal")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Kwazulu-Natal")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iKwaZulu-Natal")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "GaZulu-Natala")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Hazolo-Natala")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ss", "ssw", 428, "KwaZulu-Natali")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "KwaZulu-Natal")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Kwazulu-Natal")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "HaZulu-Natal")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "KwaZulu-Natala")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "KwaZulu-Natali")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KZN = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-KZN");
            
            /// <summary>
            /// Free State
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-FS")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Vrystaat")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Free State")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iFreyistata")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Freistata")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Freistata", SubdivisionNameLocalVariant="Foreisetata")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Foreisetata")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Free State")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "Fureisitata")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Freyistata")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Fuleyisitata", SubdivisionNameLocalVariant="Freyisitata")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _FS = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-FS");
            
            /// <summary>
            /// Western Cape
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(428, "ZA-WC")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("af", "afr", 428, "Wes-Kaap")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 428, "Western Cape")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("nr", "nbl", 428, "iTjhingalanga-Kapa")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute(null, "nso", 428, "Kapa Bodikela")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("st", "sot", 428, "Kapa Bophirimela")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("tn", "tsn", 428, "Kapa Bophirima")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ts", "tso", 428, "Kapa-Vupeladyambu")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ve", "ven", 428, "Kapa Vhukovhela")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("xh", "xho", 428, "Ntshona-Koloni")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("zu", "zul", 428, "Ntshonalanga-Kapa", SubdivisionNameLocalVariant="Ntshonalanga-Koloni")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _WC = new DataStandardizer.Geography.Iso3166Part2Subdivision("ZA-WC");
            #endregion
        }
    }
}

