//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.Geography
{
    
    
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("ar", "ara", 161, "‘amālah")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 161, "prefecture", "prefectures")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 161, "préfecture")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("ar", "ara", 249, "iqlīm")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 249, "province", "provinces")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 249, "province")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("ar", "ara", 287, "jihāt")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 287, "region", "regions")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 287, "région")]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("ar", "ara", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        public static class MA
        {
            
            #region prefectures
            /// <summary>
            /// Oujda-Angad
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-OUJ", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Oujda-Angad", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _OUJ = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-OUJ");
            
            /// <summary>
            /// Tanger-Assilah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-TNG", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Tanger-Assilah", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TNG = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TNG");
            
            /// <summary>
            /// M’diq-Fnideq
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-MDF", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "M’diq-Fnideq", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MDF = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-MDF");
            
            /// <summary>
            /// Inezgane-Ait Melloul
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-INE", "MA-09")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Inezgane-Ait Melloul", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _INE = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-INE");
            
            /// <summary>
            /// Fès
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-FES", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Fès", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _FES = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-FES");
            
            /// <summary>
            /// Meknès
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-MEK", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Meknès", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MEK = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-MEK");
            
            /// <summary>
            /// Rabat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-RAB", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Rabat", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _RAB = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-RAB");
            
            /// <summary>
            /// Salé
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-SAL", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Salé", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SAL = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SAL");
            
            /// <summary>
            /// Agadir-Ida-Ou-Tanane
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-AGD", "MA-09")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Agadir-Ida-Ou-Tanane", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _AGD = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-AGD");
            
            /// <summary>
            /// Skhirate-Témara
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-SKH", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Skhirate-Témara", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SKH = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SKH");
            
            /// <summary>
            /// Marrakech
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-MAR", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Marrakech", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MAR = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-MAR");
            
            /// <summary>
            /// Mohammadia
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-MOH", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Mohammadia", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MOH = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-MOH");
            
            /// <summary>
            /// Casablanca
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(161, "MA-CAS", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 161, "Casablanca", SubdivisionNameLocalVariant="Dar el Beïda", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _CAS = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-CAS");
            #endregion
            
            #region provinces
            /// <summary>
            /// Sidi Kacem
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-SIK", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Sidi Kacem", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SIK = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SIK");
            
            /// <summary>
            /// Sidi Slimane
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-SIL", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Sidi Slimane", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SIL = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SIL");
            
            /// <summary>
            /// Essaouira
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-ESI", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Essaouira", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ESI = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-ESI");
            
            /// <summary>
            /// Al Haouz
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-HAO", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Al Haouz", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _HAO = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-HAO");
            
            /// <summary>
            /// Azilal
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-AZI", "MA-05")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Azilal", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _AZI = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-AZI");
            
            /// <summary>
            /// Béni Mellal
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-BEM", "MA-05")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Béni Mellal", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BEM = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-BEM");
            
            /// <summary>
            /// El Kelâa des Sraghna
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-KES", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "El Kelâa des Sraghna", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KES = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-KES");
            
            /// <summary>
            /// Fquih Ben Salah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-FQH", "MA-05")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Fquih Ben Salah", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _FQH = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-FQH");
            
            /// <summary>
            /// Khénifra
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-KHN", "MA-05")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Khénifra", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KHN = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-KHN");
            
            /// <summary>
            /// Khouribga
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-KHO", "MA-05")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Khouribga", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KHO = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-KHO");
            
            /// <summary>
            /// Benslimane
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-BES", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Benslimane", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BES = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-BES");
            
            /// <summary>
            /// Chichaoua
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-CHI", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Chichaoua", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _CHI = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-CHI");
            
            /// <summary>
            /// Sidi Bennour
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-SIB", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Sidi Bennour", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SIB = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SIB");
            
            /// <summary>
            /// Médiouna
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-MED", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Médiouna", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MED = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-MED");
            
            /// <summary>
            /// Kénitra
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-KEN", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Kénitra", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KEN = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-KEN");
            
            /// <summary>
            /// Taza
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TAZ", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Taza", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TAZ = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TAZ");
            
            /// <summary>
            /// Settat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-SET", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Settat", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SET = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SET");
            
            /// <summary>
            /// El Jadida
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-JDI", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "El Jadida", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JDI = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-JDI");
            
            /// <summary>
            /// Chtouka-Ait Baha
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-CHT", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Chtouka-Ait Baha", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _CHT = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-CHT");
            
            /// <summary>
            /// Taourirt
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TAI", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Taourirt", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TAI = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TAI");
            
            /// <summary>
            /// Taounate
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TAO", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Taounate", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TAO = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TAO");
            
            /// <summary>
            /// Sefrou
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-SEF", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Sefrou", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SEF = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SEF");
            
            /// <summary>
            /// Moulay Yacoub
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-MOU", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Moulay Yacoub", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MOU = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-MOU");
            
            /// <summary>
            /// Ifrane
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-IFR", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Ifrane", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _IFR = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-IFR");
            
            /// <summary>
            /// El Hajeb
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-HAJ", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "El Hajeb", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _HAJ = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-HAJ");
            
            /// <summary>
            /// Boulemane
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-BOM", "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Boulemane", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BOM = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-BOM");
            
            /// <summary>
            /// Berrechid
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-BRR", "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Berrechid", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BRR = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-BRR");
            
            /// <summary>
            /// Rehamna
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-REH", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Rehamna", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _REH = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-REH");
            
            /// <summary>
            /// Guelmim
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-GUE", "MA-10")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Guelmim", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _GUE = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-GUE");
            
            /// <summary>
            /// Youssoufia
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-YUS", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Youssoufia", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _YUS = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-YUS");
            
            /// <summary>
            /// Jerada
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-JRA", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Jerada", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JRA = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-JRA");
            
            /// <summary>
            /// Guercif
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-GUF", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Guercif", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _GUF = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-GUF");
            
            /// <summary>
            /// Figuig
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-FIG", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Figuig", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _FIG = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-FIG");
            
            /// <summary>
            /// Driouch
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-DRI", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Driouch", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _DRI = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-DRI");
            
            /// <summary>
            /// Berkane
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-BER", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Berkane", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BER = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-BER");
            
            /// <summary>
            /// Tétouan
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TET", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Tétouan", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TET = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TET");
            
            /// <summary>
            /// Ouezzane
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-OUZ", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Ouezzane", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _OUZ = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-OUZ");
            
            /// <summary>
            /// Larache
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-LAR", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Larache", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _LAR = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-LAR");
            
            /// <summary>
            /// Al Hoceïma
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-HOC", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Al Hoceïma", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _HOC = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-HOC");
            
            /// <summary>
            /// Fahs-Anjra
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-FAH", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Fahs-Anjra", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _FAH = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-FAH");
            
            /// <summary>
            /// Safi
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-SAF", "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Safi", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SAF = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SAF");
            
            /// <summary>
            /// Nador
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-NAD", "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Nador", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _NAD = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-NAD");
            
            /// <summary>
            /// Oued Ed-Dahab (EH)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-OUD", "MA-12")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Oued Ed-Dahab (EH)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _OUD = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-OUD");
            
            /// <summary>
            /// Aousserd (EH)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-AOU", "MA-12")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Aousserd (EH)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _AOU = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-AOU");
            
            /// <summary>
            /// Tarfaya (EH-partial)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TAF", "MA-11")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Tarfaya (EH-partial)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TAF = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TAF");
            
            /// <summary>
            /// Chefchaouen
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-CHE", "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Chefchaouen", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _CHE = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-CHE");
            
            /// <summary>
            /// Es-Semara (EH-partial)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-ESM", "MA-11")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Es-Semara (EH-partial)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ESM = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-ESM");
            
            /// <summary>
            /// Errachidia
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-ERR", "MA-08")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Errachidia", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ERR = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-ERR");
            
            /// <summary>
            /// Midelt
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-MID", "MA-08")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Midelt", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MID = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-MID");
            
            /// <summary>
            /// Laâyoune (EH)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-LAA", "MA-11")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Laâyoune (EH)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _LAA = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-LAA");
            
            /// <summary>
            /// Tinghir
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TIN", "MA-08")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Tinghir", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TIN = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TIN");
            
            /// <summary>
            /// Zagora
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-ZAG", "MA-08")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Zagora", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ZAG = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-ZAG");
            
            /// <summary>
            /// Taroudannt
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TAR", "MA-09")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Taroudannt", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TAR = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TAR");
            
            /// <summary>
            /// Ouarzazate
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-OUA", "MA-08")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Ouarzazate", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _OUA = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-OUA");
            
            /// <summary>
            /// Tiznit
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TIZ", "MA-09")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Tiznit", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TIZ = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TIZ");
            
            /// <summary>
            /// Assa-Zag (EH-partial)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-ASZ", "MA-10")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Assa-Zag (EH-partial)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ASZ = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-ASZ");
            
            /// <summary>
            /// Nouaceur
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-NOU", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Nouaceur", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _NOU = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-NOU");
            
            /// <summary>
            /// Sidi Ifni
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-SIF", "MA-10")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Sidi Ifni", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SIF = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-SIF");
            
            /// <summary>
            /// Tan-Tan (EH-partial)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TNT", "MA-10")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Tan-Tan (EH-partial)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TNT = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TNT");
            
            /// <summary>
            /// Boujdour (EH)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-BOD", "MA-11")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Boujdour (EH)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BOD = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-BOD");
            
            /// <summary>
            /// Tata
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-TAT", "MA-09")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Tata", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _TAT = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-TAT");
            
            /// <summary>
            /// Khémisset
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(249, "MA-KHE", "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 249, "Khémisset", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KHE = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-KHE");
            #endregion
            
            #region regions
            /// <summary>
            /// Laâyoune-Sakia El Hamra (EH-partial)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-11")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Laâyoune-Sakia El Hamra (EH-partial)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _11 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-11");
            
            /// <summary>
            /// Guelmim-Oued Noun (EH-partial)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-10")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Guelmim-Oued Noun (EH-partial)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _10 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-10");
            
            /// <summary>
            /// L'Oriental
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "L\'Oriental", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _02 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-02");
            
            /// <summary>
            /// Fès-Meknès
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Fès-Meknès", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _03 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-03");
            
            /// <summary>
            /// Marrakech-Safi
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-07")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Marrakech-Safi", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _07 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-07");
            
            /// <summary>
            /// Drâa-Tafilalet
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-08")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Drâa-Tafilalet", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _08 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-08");
            
            /// <summary>
            /// Casablanca-Settat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-06")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Casablanca-Settat", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _06 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-06");
            
            /// <summary>
            /// Souss-Massa
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-09")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Souss-Massa", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _09 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-09");
            
            /// <summary>
            /// Dakhla-Oued Ed-Dahab (EH)
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-12")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Dakhla-Oued Ed-Dahab (EH)", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _12 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-12");
            
            /// <summary>
            /// Béni Mellal-Khénifra
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-05")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Béni Mellal-Khénifra", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _05 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-05");
            
            /// <summary>
            /// Tanger-Tétouan-Al Hoceïma
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Tanger-Tétouan-Al Hoceïma", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _01 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-01");
            
            /// <summary>
            /// Rabat-Salé-Kénitra
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(287, "MA-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 287, "Rabat-Salé-Kénitra", RomanizationSystem="conventional names")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _04 = new DataStandardizer.Geography.Iso3166Part2Subdivision("MA-04");
            #endregion
        }
    }
}

