//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.Geography
{
    
    
    /// <summary>
    /// ISO 3166-2, Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 215, "district", "districts")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 215, "district")]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("en", "eng", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("ms", "msa", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("ta", "tam", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("zh", "zho", IsAdministrative=true)]
        public static class SG
        {
            
            #region districts
            /// <summary>
            /// South East
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(215, "SG-04")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 215, "South East")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _04 = new DataStandardizer.Geography.Iso3166Part2Subdivision("SG-04");
            
            /// <summary>
            /// South West
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(215, "SG-05")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 215, "South West")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _05 = new DataStandardizer.Geography.Iso3166Part2Subdivision("SG-05");
            
            /// <summary>
            /// North West
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(215, "SG-03")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 215, "North West")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _03 = new DataStandardizer.Geography.Iso3166Part2Subdivision("SG-03");
            
            /// <summary>
            /// North East
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(215, "SG-02")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 215, "North East")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _02 = new DataStandardizer.Geography.Iso3166Part2Subdivision("SG-02");
            
            /// <summary>
            /// Central Singapore
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(215, "SG-01")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("en", "eng", 215, "Central Singapore")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _01 = new DataStandardizer.Geography.Iso3166Part2Subdivision("SG-01");
            #endregion
        }
    }
}

