//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.Geography
{
    
    
    /// <summary>
    /// ISO 3166-2, Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("ar", "ara", 316, "muḩāfaz̧ah")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 316, "governorate", "governorates")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 316, "gouvernorat")]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("ar", "ara", IsAdministrative=true)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        public static class EG
        {
            
            #region governorates
            /// <summary>
            /// Al Qalyūbīyah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-KB")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Qalyūbīyah", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KB = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-KB");
            
            /// <summary>
            /// Janūb Sīnā'
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-JS")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Janūb Sīnā\'", SubdivisionNameLocalVariant="South Sinai", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JS = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-JS");
            
            /// <summary>
            /// Al Ismā'īlīyah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-IS")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Ismā\'īlīyah", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _IS = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-IS");
            
            /// <summary>
            /// Al Jīzah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-GZ")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Jīzah", SubdivisionNameLocalVariant="Giza", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _GZ = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-GZ");
            
            /// <summary>
            /// Al Gharbīyah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-GH")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Gharbīyah", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _GH = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-GH");
            
            /// <summary>
            /// Al Fayyūm
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-FYM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Fayyūm", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _FYM = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-FYM");
            
            /// <summary>
            /// Al Iskandarīyah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-ALX")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Iskandarīyah", SubdivisionNameLocalVariant="Alexandria", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ALX = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-ALX");
            
            /// <summary>
            /// Ad Daqahlīyah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-DK")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Ad Daqahlīyah", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _DK = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-DK");
            
            /// <summary>
            /// Kafr ash Shaykh
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-KFS")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Kafr ash Shaykh", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KFS = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-KFS");
            
            /// <summary>
            /// Banī Suwayf
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-BNS")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Banī Suwayf", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BNS = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-BNS");
            
            /// <summary>
            /// Al Baḩr al Aḩmar
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-BA")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Baḩr al Aḩmar", SubdivisionNameLocalVariant="Red Sea", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BA = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-BA");
            
            /// <summary>
            /// Asyūţ
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-AST")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Asyūţ", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _AST = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-AST");
            
            /// <summary>
            /// Aswān
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-ASN")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Aswān", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ASN = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-ASN");
            
            /// <summary>
            /// Dumyāţ
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-DT")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Dumyāţ", SubdivisionNameLocalVariant="Damietta", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _DT = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-DT");
            
            /// <summary>
            /// Al Qāhirah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-C")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Qāhirah", SubdivisionNameLocalVariant="Cairo", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _C = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-C");
            
            /// <summary>
            /// Al Uqşur
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-LX")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Uqşur", SubdivisionNameLocalVariant="Luxor", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _LX = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-LX");
            
            /// <summary>
            /// Al Minyā
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-MN")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Minyā", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MN = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-MN");
            
            /// <summary>
            /// Qinā
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-KN")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Qinā", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KN = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-KN");
            
            /// <summary>
            /// Al Wādī al Jadīd
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-WAD")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Wādī al Jadīd", SubdivisionNameLocalVariant="New Valley", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _WAD = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-WAD");
            
            /// <summary>
            /// As Suways
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-SUZ")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "As Suways", SubdivisionNameLocalVariant="Suez", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SUZ = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-SUZ");
            
            /// <summary>
            /// Shamāl Sīnā'
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-SIN")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Shamāl Sīnā\'", SubdivisionNameLocalVariant="North Sinai", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SIN = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-SIN");
            
            /// <summary>
            /// Al Buḩayrah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-BH")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Buḩayrah", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BH = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-BH");
            
            /// <summary>
            /// Sūhāj
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-SHG")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Sūhāj", SubdivisionNameLocalVariant="Sohag", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SHG = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-SHG");
            
            /// <summary>
            /// Būr Sa‘īd
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-PTS")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Būr Sa‘īd", SubdivisionNameLocalVariant="Port Said", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PTS = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-PTS");
            
            /// <summary>
            /// Maţrūḩ
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-MT")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Maţrūḩ", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MT = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-MT");
            
            /// <summary>
            /// Ash Sharqīyah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-SHR")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Ash Sharqīyah", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SHR = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-SHR");
            
            /// <summary>
            /// Al Minūfīyah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(316, "EG-MNF")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("ar", "ara", 316, "Al Minūfīyah", RomanizationSystem="BGN/PCGN 1956")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MNF = new DataStandardizer.Geography.Iso3166Part2Subdivision("EG-MNF");
            #endregion
        }
    }
}

