//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStandardizer.Geography
{
    
    
    /// <summary>
    /// ISO 3166-2, Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code
    /// </summary>
    public readonly partial struct Iso3166Part2Subdivision
    {
        
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 159, "geographical unit", "geographical units")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 159, "unité géographique")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 205, "province", "provinces")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 205, "province")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("id", "ind", 205, "provinsi")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 269, "special region", "special regions")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 269, "région spéciale")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("id", "ind", 269, "daerah istimewa")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("en", "eng", 358, "capital district", "capital districts")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("fr", "fra", 358, "district de la capitale")]
        [DataStandardizer.Geography.Iso3166SubdivisionCategoryNameAttribute("id", "ind", 358, "daerah khusus ibukota")]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("en", "eng", IsAdministrative=false)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("fr", "fra", IsAdministrative=false)]
        [DataStandardizer.Geography.Iso3166LanguageAttribute("id", "ind", IsAdministrative=true)]
        public static class ID
        {
            
            #region geographical units
            /// <summary>
            /// Sulawesi
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(159, "ID-SL")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 159, "Sulawesi")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SL = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SL");
            
            /// <summary>
            /// Papua
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(159, "ID-PP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 159, "Papua")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PP = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-PP");
            
            /// <summary>
            /// Jawa
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(159, "ID-JW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 159, "Jawa")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JW = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-JW");
            
            /// <summary>
            /// Kalimantan
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(159, "ID-KA")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 159, "Kalimantan")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KA = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-KA");
            
            /// <summary>
            /// Nusa Tenggara
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(159, "ID-NU")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 159, "Nusa Tenggara")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _NU = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-NU");
            
            /// <summary>
            /// Maluku
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(159, "ID-ML")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 159, "Maluku")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ML = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-ML");
            
            /// <summary>
            /// Sumatera
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(159, "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 159, "Sumatera")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SM = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SM");
            #endregion
            
            #region provinces
            /// <summary>
            /// Kalimantan Selatan
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-KS", "ID-KA")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Kalimantan Selatan")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KS = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-KS");
            
            /// <summary>
            /// Jawa Timur
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-JI", "ID-JW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Jawa Timur")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JI = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-JI");
            
            /// <summary>
            /// Kalimantan Timur
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-KI", "ID-KA")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Kalimantan Timur")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KI = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-KI");
            
            /// <summary>
            /// Kalimantan Barat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-KB", "ID-KA")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Kalimantan Barat")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KB = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-KB");
            
            /// <summary>
            /// Jawa Tengah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-JT", "ID-JW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Jawa Tengah")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JT = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-JT");
            
            /// <summary>
            /// Kalimantan Tengah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-KT", "ID-KA")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Kalimantan Tengah")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KT = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-KT");
            
            /// <summary>
            /// Banten
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-BT", "ID-JW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Banten")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BT = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-BT");
            
            /// <summary>
            /// Jawa Barat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-JB", "ID-JW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Jawa Barat")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JB = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-JB");
            
            /// <summary>
            /// Kalimantan Utara
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-KU", "ID-KA")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Kalimantan Utara")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KU = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-KU");
            
            /// <summary>
            /// Nusa Tenggara Barat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-NB", "ID-NU")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Nusa Tenggara Barat")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _NB = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-NB");
            
            /// <summary>
            /// Maluku Utara
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-MU", "ID-ML")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Maluku Utara")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MU = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-MU");
            
            /// <summary>
            /// Sumatera Utara
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-SU", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sumatera Utara")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SU = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SU");
            
            /// <summary>
            /// Sumatera Selatan
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-SS", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sumatera Selatan")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SS = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SS");
            
            /// <summary>
            /// Sumatera Barat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-SB", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sumatera Barat")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SB = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SB");
            
            /// <summary>
            /// Riau
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-RI", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Riau")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _RI = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-RI");
            
            /// <summary>
            /// Lampung
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-LA", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Lampung")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _LA = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-LA");
            
            /// <summary>
            /// Kepulauan Riau
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-KR", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Kepulauan Riau")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _KR = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-KR");
            
            /// <summary>
            /// Jambi
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-JA", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Jambi")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JA = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-JA");
            
            /// <summary>
            /// Bengkulu
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-BE", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Bengkulu")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BE = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-BE");
            
            /// <summary>
            /// Kepulauan Bangka Belitung
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-BB", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Kepulauan Bangka Belitung")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BB = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-BB");
            
            /// <summary>
            /// Aceh
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-AC", "ID-SM")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Aceh")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _AC = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-AC");
            
            /// <summary>
            /// Sulawesi Tengah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-ST", "ID-SL")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sulawesi Tengah")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _ST = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-ST");
            
            /// <summary>
            /// Sulawesi Barat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-SR", "ID-SL")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sulawesi Barat")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SR = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SR");
            
            /// <summary>
            /// Sulawesi Selatan
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-SN", "ID-SL")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sulawesi Selatan")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SN = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SN");
            
            /// <summary>
            /// Sulawesi Tenggara
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-SG", "ID-SL")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sulawesi Tenggara")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SG = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SG");
            
            /// <summary>
            /// Sulawesi Utara
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-SA", "ID-SL")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Sulawesi Utara")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _SA = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-SA");
            
            /// <summary>
            /// Gorontalo
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-GO", "ID-SL")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Gorontalo")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _GO = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-GO");
            
            /// <summary>
            /// Papua Tengah
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-PT", "ID-PP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Papua Tengah")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PT = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-PT");
            
            /// <summary>
            /// Papua Selatan
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-PS", "ID-PP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Papua Selatan")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PS = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-PS");
            
            /// <summary>
            /// Papua Pengunungan
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-PE", "ID-PP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Papua Pengunungan")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PE = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-PE");
            
            /// <summary>
            /// Papua Barat Daya
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-PD", "ID-PP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Papua Barat Daya")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PD = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-PD");
            
            /// <summary>
            /// Papua Barat
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-PB", "ID-PP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Papua Barat")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PB = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-PB");
            
            /// <summary>
            /// Papua
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-PA", "ID-PP")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Papua")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _PA = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-PA");
            
            /// <summary>
            /// Bali
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-BA", "ID-NU")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Bali")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _BA = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-BA");
            
            /// <summary>
            /// Maluku
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-MA", "ID-ML")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Maluku")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _MA = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-MA");
            
            /// <summary>
            /// Nusa Tenggara Timur
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(205, "ID-NT", "ID-NU")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 205, "Nusa Tenggara Timur")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _NT = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-NT");
            #endregion
            
            #region special regions
            /// <summary>
            /// Yogyakarta
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(269, "ID-YO", "ID-JW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 269, "Yogyakarta", SubdivisionNameLocalVariant="DI Yogya; DIY")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _YO = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-YO");
            #endregion
            
            #region capital districts
            /// <summary>
            /// Jakarta Raya
            /// </summary>
            [DataStandardizer.Geography.Iso3166SubdivisionCodeAttribute(358, "ID-JK", "ID-JW")]
            [DataStandardizer.Geography.Iso3166SubdivisionNameAttribute("id", "ind", 358, "Jakarta Raya", SubdivisionNameLocalVariant="DKI Jakarta; DKI")]
            public static readonly DataStandardizer.Geography.Iso3166Part2Subdivision _JK = new DataStandardizer.Geography.Iso3166Part2Subdivision("ID-JK");
            #endregion
        }
    }
}

