<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard2.0;net8.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Authors>matthew25187</Authors>
    <Product>Data Standardizer</Product>
    <Description>Data Standardizer provides implementations of various internationally recognised standards in data processing, covering topics ranging from languages to currencies and geographical entities. With strongly-typed enumerations for each standard (where applicable) or other targeted data types, you can represent these elements in your code such that errors with invalid values are minimised.

Includes:
- Supports use of ISO 4217, "Codes for the representation of currencies and funds"
  - Table A.1 – Current currency &amp; funds code list
  - Table A.3 – List of codes for historic denominations of currencies &amp; funds
- Money data type, combining an amount with an ISO 4217 currency code to manage a monetary value.</Description>
    <Copyright>Copyright © 2024-2025, Matthew25187. All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/matthew25187/DataStandardizer</PackageProjectUrl>
    <PackageIcon>054-doc_web.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/matthew25187/DataStandardizer.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>data;standard;money;amount;currency</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
    <NetStandardImplicitPackageVersion>2.0.3</NetStandardImplicitPackageVersion>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="global.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\images\054-doc_web.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.0'">
    <PackageReference Include="System.ValueTuple" Version="[4.5.0]" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.0' Or '$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataStandardizer.Core\DataStandardizer.Core.csproj" />
  </ItemGroup>

</Project>
