<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard2.0;net8.0</TargetFrameworks>
    <NetStandardImplicitPackageVersion>2.0.3</NetStandardImplicitPackageVersion>
    <CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
        <CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>matthew25187</Authors>
    <Product>Data Standardizer</Product>
    <Description>Data Standardizer provides implementations of various internationally recognised standards in data processing, covering topics ranging from languages to currencies and geographical entities. With strongly-typed enumerations for each standard (where applicable) or other targeted data types, you can represent these elements in your code such that errors with invalid values are minimised.

Includes:
- Supports use of IETF BCP 47 language tags as defined by RFC 5646.</Description>
    <Copyright>Copyright © 2025, Matthew25187. All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/matthew25187/DataStandardizer</PackageProjectUrl>
    <PackageIcon>054-doc_web.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/matthew25187/DataStandardizer.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>data;standard;ietf;bcp 47;language;tag</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="global.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\images\054-doc_web.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.0'">
    <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.0' Or '$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataStandardizer.Geography\DataStandardizer.Geography.csproj" />
    <ProjectReference Include="..\DataStandardizer.Language\DataStandardizer.Language.csproj" />
  </ItemGroup>

</Project>
