//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if NETCOREAPP3_0_OR_GREATER
#nullable enable
#endif

namespace DataStandardizer.Language
{
    
    
    public readonly partial struct Iso639Part3Language : DataStandardizer.Core.IStringEnum, System.IEquatable<DataStandardizer.Language.Iso639Part3Language>
    {
        
        #region Public Fields
        /// <summary>
        /// Iaai
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iaai", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iaai", InvertedName="Iaai")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iai = new DataStandardizer.Language.Iso639Part3Language("iai");
        
        /// <summary>
        /// Iatmul
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iatmul", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iatmul", InvertedName="Iatmul")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ian = new DataStandardizer.Language.Iso639Part3Language("ian");
        
        /// <summary>
        /// Purari
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Purari", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Purari", InvertedName="Purari")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iar = new DataStandardizer.Language.Iso639Part3Language("iar");
        
        /// <summary>
        /// Iban
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iban", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iban", InvertedName="Iban", Part2BCode="iba", Part2TCode="iba")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iba = new DataStandardizer.Language.Iso639Part3Language("iba");
        
        /// <summary>
        /// Ibibio
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibibio", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibibio", InvertedName="Ibibio")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibb = new DataStandardizer.Language.Iso639Part3Language("ibb");
        
        /// <summary>
        /// Iwaidja
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iwaidja", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iwaidja", InvertedName="Iwaidja")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibd = new DataStandardizer.Language.Iso639Part3Language("ibd");
        
        /// <summary>
        /// Akpes
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Akpes", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Akpes", InvertedName="Akpes")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibe = new DataStandardizer.Language.Iso639Part3Language("ibe");
        
        /// <summary>
        /// Ibanag
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibanag", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibanag", InvertedName="Ibanag")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibg = new DataStandardizer.Language.Iso639Part3Language("ibg");
        
        /// <summary>
        /// Bih
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Bih", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Bih", InvertedName="Bih")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibh = new DataStandardizer.Language.Iso639Part3Language("ibh");
        
        /// <summary>
        /// Ibaloi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibaloi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibaloi", InvertedName="Ibaloi")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibl = new DataStandardizer.Language.Iso639Part3Language("ibl");
        
        /// <summary>
        /// Agoi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Agoi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Agoi", InvertedName="Agoi")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibm = new DataStandardizer.Language.Iso639Part3Language("ibm");
        
        /// <summary>
        /// Ibino
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibino", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibino", InvertedName="Ibino")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibn = new DataStandardizer.Language.Iso639Part3Language("ibn");
        
        /// <summary>
        /// Igbo
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Igbo", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Igbo", InvertedName="Igbo", Part1Code="ig", Part2BCode="ibo", Part2TCode="ibo")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibo = new DataStandardizer.Language.Iso639Part3Language("ibo");
        
        /// <summary>
        /// Ibuoro
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibuoro", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibuoro", InvertedName="Ibuoro")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibr = new DataStandardizer.Language.Iso639Part3Language("ibr");
        
        /// <summary>
        /// Ibu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibu", InvertedName="Ibu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ibu = new DataStandardizer.Language.Iso639Part3Language("ibu");
        
        /// <summary>
        /// Ibani
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibani", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibani", InvertedName="Ibani")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iby = new DataStandardizer.Language.Iso639Part3Language("iby");
        
        /// <summary>
        /// Ede Ica
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ede Ica", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ede Ica", InvertedName="Ede Ica")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ica = new DataStandardizer.Language.Iso639Part3Language("ica");
        
        /// <summary>
        /// Etkywan
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Etkywan", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Etkywan", InvertedName="Etkywan")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ich = new DataStandardizer.Language.Iso639Part3Language("ich");
        
        /// <summary>
        /// Icelandic Sign Language
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Icelandic Sign Language", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Icelandic Sign Language", InvertedName="Icelandic Sign Language")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @icl = new DataStandardizer.Language.Iso639Part3Language("icl");
        
        /// <summary>
        /// Islander Creole English
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Islander Creole English", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Islander Creole English", InvertedName="Creole English, Islander")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @icr = new DataStandardizer.Language.Iso639Part3Language("icr");
        
        /// <summary>
        /// Idakho-Isukha-Tiriki
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Idakho-Isukha-Tiriki", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Idakho-Isukha-Tiriki Luidakho-Luisukha-Lutirichi", InvertedName="Idakho-Isukha-Tiriki Luidakho-Luisukha-Lutirichi", MacrolanguageCode="luy")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ida = new DataStandardizer.Language.Iso639Part3Language("ida");
        
        /// <summary>
        /// Indo-Portuguese
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Indo-Portuguese", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Indo-Portuguese", InvertedName="Indo-Portuguese")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @idb = new DataStandardizer.Language.Iso639Part3Language("idb");
        
        /// <summary>
        /// Idon
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Idon", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ajiya Idon", InvertedName="Ajiya Idon")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @idc = new DataStandardizer.Language.Iso639Part3Language("idc");
        
        /// <summary>
        /// Ede Idaca
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ede Idaca", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ede Idaca", InvertedName="Ede Idaca")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @idd = new DataStandardizer.Language.Iso639Part3Language("idd");
        
        /// <summary>
        /// Idere
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Idere", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Idere", InvertedName="Idere")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ide = new DataStandardizer.Language.Iso639Part3Language("ide");
        
        /// <summary>
        /// Idi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Idi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Idi", InvertedName="Idi")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @idi = new DataStandardizer.Language.Iso639Part3Language("idi");
        
        /// <summary>
        /// Ido
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ido", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Constructed, PrintName="Ido", InvertedName="Ido", Part1Code="io", Part2BCode="ido", Part2TCode="ido")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ido = new DataStandardizer.Language.Iso639Part3Language("ido");
        
        /// <summary>
        /// Indri
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Indri", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Indri", InvertedName="Indri")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @idr = new DataStandardizer.Language.Iso639Part3Language("idr");
        
        /// <summary>
        /// Idesa
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Idesa", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Idesa", InvertedName="Idesa")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ids = new DataStandardizer.Language.Iso639Part3Language("ids");
        
        /// <summary>
        /// Idaté
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Idaté", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Idaté", InvertedName="Idaté")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @idt = new DataStandardizer.Language.Iso639Part3Language("idt");
        
        /// <summary>
        /// Idoma
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Idoma", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Idoma", InvertedName="Idoma")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @idu = new DataStandardizer.Language.Iso639Part3Language("idu");
        
        /// <summary>
        /// Amganad Ifugao
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Amganad Ifugao", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Amganad Ifugao", InvertedName="Ifugao, Amganad")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ifa = new DataStandardizer.Language.Iso639Part3Language("ifa");
        
        /// <summary>
        /// Batad Ifugao
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Batad Ifugao", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ayangan Ifugao Batad Ifugao", InvertedName="Ifugao, Ayangan Ifugao, Batad")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ifb = new DataStandardizer.Language.Iso639Part3Language("ifb");
        
        /// <summary>
        /// Ifè
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ifè", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ifè", InvertedName="Ifè")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ife = new DataStandardizer.Language.Iso639Part3Language("ife");
        
        /// <summary>
        /// Ifo
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ifo", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Ifo", InvertedName="Ifo")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iff = new DataStandardizer.Language.Iso639Part3Language("iff");
        
        /// <summary>
        /// Tuwali Ifugao
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Tuwali Ifugao", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Tuwali Ifugao", InvertedName="Ifugao, Tuwali")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ifk = new DataStandardizer.Language.Iso639Part3Language("ifk");
        
        /// <summary>
        /// Teke-Fuumu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Teke-Fuumu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Teke-Fuumu", InvertedName="Teke-Fuumu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ifm = new DataStandardizer.Language.Iso639Part3Language("ifm");
        
        /// <summary>
        /// Mayoyao Ifugao
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Mayoyao Ifugao", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Mayoyao Ifugao", InvertedName="Ifugao, Mayoyao")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ifu = new DataStandardizer.Language.Iso639Part3Language("ifu");
        
        /// <summary>
        /// Keley-I Kallahan
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Keley-I Kallahan", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Keley-I Kallahan", InvertedName="Kallahan, Keley-I")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ify = new DataStandardizer.Language.Iso639Part3Language("ify");
        
        /// <summary>
        /// Ebira
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ebira", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ebira", InvertedName="Ebira")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @igb = new DataStandardizer.Language.Iso639Part3Language("igb");
        
        /// <summary>
        /// Igede
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Igede", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Igede", InvertedName="Igede")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ige = new DataStandardizer.Language.Iso639Part3Language("ige");
        
        /// <summary>
        /// Igana
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Igana", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Igana", InvertedName="Igana")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @igg = new DataStandardizer.Language.Iso639Part3Language("igg");
        
        /// <summary>
        /// Igala
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Igala", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Igala", InvertedName="Igala")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @igl = new DataStandardizer.Language.Iso639Part3Language("igl");
        
        /// <summary>
        /// Kanggape
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Kanggape", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Kanggape", InvertedName="Kanggape")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @igm = new DataStandardizer.Language.Iso639Part3Language("igm");
        
        /// <summary>
        /// Ignaciano
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ignaciano", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ignaciano", InvertedName="Ignaciano")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ign = new DataStandardizer.Language.Iso639Part3Language("ign");
        
        /// <summary>
        /// Isebe
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isebe", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isebe", InvertedName="Isebe")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @igo = new DataStandardizer.Language.Iso639Part3Language("igo");
        
        /// <summary>
        /// Interglossa
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Interglossa", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Constructed, PrintName="Interglossa", InvertedName="Interglossa")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @igs = new DataStandardizer.Language.Iso639Part3Language("igs");
        
        /// <summary>
        /// Igwe
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Igwe", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Igwe", InvertedName="Igwe")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @igw = new DataStandardizer.Language.Iso639Part3Language("igw");
        
        /// <summary>
        /// Iha Based Pidgin
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iha Based Pidgin", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iha Based Pidgin", InvertedName="Iha Based Pidgin")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ihb = new DataStandardizer.Language.Iso639Part3Language("ihb");
        
        /// <summary>
        /// Ihievbe
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ihievbe", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ihievbe", InvertedName="Ihievbe")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ihi = new DataStandardizer.Language.Iso639Part3Language("ihi");
        
        /// <summary>
        /// Iha
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iha", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iha", InvertedName="Iha")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ihp = new DataStandardizer.Language.Iso639Part3Language("ihp");
        
        /// <summary>
        /// Bidhawal
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Bidhawal", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Bidhawal", InvertedName="Bidhawal")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ihw = new DataStandardizer.Language.Iso639Part3Language("ihw");
        
        /// <summary>
        /// Sichuan Yi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Sichuan Yi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Nuosu Sichuan Yi", InvertedName="Nuosu Yi, Sichuan", Part1Code="ii", Part2BCode="iii", Part2TCode="iii")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iii = new DataStandardizer.Language.Iso639Part3Language("iii");
        
        /// <summary>
        /// Thiin
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Thiin", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Thiin", InvertedName="Thiin")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iin = new DataStandardizer.Language.Iso639Part3Language("iin");
        
        /// <summary>
        /// Izon
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Izon", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Izon", InvertedName="Izon")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ijc = new DataStandardizer.Language.Iso639Part3Language("ijc");
        
        /// <summary>
        /// Biseni
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Biseni", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Biseni", InvertedName="Biseni")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ije = new DataStandardizer.Language.Iso639Part3Language("ije");
        
        /// <summary>
        /// Ede Ije
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ede Ije", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ede Ije", InvertedName="Ede Ije")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ijj = new DataStandardizer.Language.Iso639Part3Language("ijj");
        
        /// <summary>
        /// Kalabari
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Kalabari", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Kalabari", InvertedName="Kalabari")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ijn = new DataStandardizer.Language.Iso639Part3Language("ijn");
        
        /// <summary>
        /// Southeast Ijo
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Southeast Ijo", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Southeast Ijo", InvertedName="Ijo, Southeast")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ijs = new DataStandardizer.Language.Iso639Part3Language("ijs");
        
        /// <summary>
        /// Eastern Canadian Inuktitut
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Eastern Canadian Inuktitut", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Eastern Canadian Inuktitut", InvertedName="Inuktitut, Eastern Canadian", MacrolanguageCode="iku")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ike = new DataStandardizer.Language.Iso639Part3Language("ike");
        
        /// <summary>
        /// Ikhin-Arokho
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ikhin-Arokho", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ikhin-Arokho", InvertedName="Ikhin-Arokho")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikh = new DataStandardizer.Language.Iso639Part3Language("ikh");
        
        /// <summary>
        /// Iko
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iko", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iko", InvertedName="Iko")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iki = new DataStandardizer.Language.Iso639Part3Language("iki");
        
        /// <summary>
        /// Ika
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ika", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ika", InvertedName="Ika")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikk = new DataStandardizer.Language.Iso639Part3Language("ikk");
        
        /// <summary>
        /// Ikulu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ikulu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ikulu", InvertedName="Ikulu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikl = new DataStandardizer.Language.Iso639Part3Language("ikl");
        
        /// <summary>
        /// Olulumo-Ikom
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Olulumo-Ikom", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Olulumo-Ikom", InvertedName="Olulumo-Ikom")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iko = new DataStandardizer.Language.Iso639Part3Language("iko");
        
        /// <summary>
        /// Ikpeshi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ikpeshi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ikpeshi", InvertedName="Ikpeshi")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikp = new DataStandardizer.Language.Iso639Part3Language("ikp");
        
        /// <summary>
        /// Ikaranggal
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ikaranggal", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Ikaranggal", InvertedName="Ikaranggal")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikr = new DataStandardizer.Language.Iso639Part3Language("ikr");
        
        /// <summary>
        /// Inuit Sign Language
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inuit Sign Language", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inuit Sign Language", InvertedName="Inuit Sign Language")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iks = new DataStandardizer.Language.Iso639Part3Language("iks");
        
        /// <summary>
        /// Inuinnaqtun
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inuinnaqtun", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inuinnaqtun Western Canadian Inuktitut", InvertedName="Inuinnaqtun Inuktitut, Western Canadian", MacrolanguageCode="iku")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikt = new DataStandardizer.Language.Iso639Part3Language("ikt");
        
        /// <summary>
        /// Inuktitut
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inuktitut", DataStandardizer.Language.Iso639LanguageScope.Macrolanguage, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inuktitut", InvertedName="Inuktitut", Part1Code="iu", Part2BCode="iku", Part2TCode="iku")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iku = new DataStandardizer.Language.Iso639Part3Language("iku");
        
        /// <summary>
        /// Iku-Gora-Ankwa
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iku-Gora-Ankwa", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iku-Gora-Ankwa", InvertedName="Iku-Gora-Ankwa")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikv = new DataStandardizer.Language.Iso639Part3Language("ikv");
        
        /// <summary>
        /// Ikwere
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ikwere", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ikwere", InvertedName="Ikwere")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikw = new DataStandardizer.Language.Iso639Part3Language("ikw");
        
        /// <summary>
        /// Ik
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ik", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ik", InvertedName="Ik")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikx = new DataStandardizer.Language.Iso639Part3Language("ikx");
        
        /// <summary>
        /// Ikizu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ikizu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ikizu", InvertedName="Ikizu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ikz = new DataStandardizer.Language.Iso639Part3Language("ikz");
        
        /// <summary>
        /// Ile Ape
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ile Ape", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ile Ape", InvertedName="Ile Ape")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ila = new DataStandardizer.Language.Iso639Part3Language("ila");
        
        /// <summary>
        /// Ila
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ila", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ila", InvertedName="Ila")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilb = new DataStandardizer.Language.Iso639Part3Language("ilb");
        
        /// <summary>
        /// Interlingue
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Interlingue", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Constructed, PrintName="Interlingue Occidental", InvertedName="Interlingue Occidental", Part1Code="ie", Part2BCode="ile", Part2TCode="ile")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ile = new DataStandardizer.Language.Iso639Part3Language("ile");
        
        /// <summary>
        /// Garig-Ilgar
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Garig-Ilgar", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Garig-Ilgar", InvertedName="Garig-Ilgar")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilg = new DataStandardizer.Language.Iso639Part3Language("ilg");
        
        /// <summary>
        /// Ili Turki
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ili Turki", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ili Turki", InvertedName="Ili Turki")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ili = new DataStandardizer.Language.Iso639Part3Language("ili");
        
        /// <summary>
        /// Ilongot
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ilongot", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ilongot", InvertedName="Ilongot")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilk = new DataStandardizer.Language.Iso639Part3Language("ilk");
        
        /// <summary>
        /// Iranun (Malaysia)
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iranun (Malaysia)", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iranun (Malaysia)", InvertedName="Iranun (Malaysia)")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilm = new DataStandardizer.Language.Iso639Part3Language("ilm");
        
        /// <summary>
        /// Iloko
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iloko", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iloko", InvertedName="Iloko", Part2BCode="ilo", Part2TCode="ilo")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilo = new DataStandardizer.Language.Iso639Part3Language("ilo");
        
        /// <summary>
        /// Iranun (Philippines)
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iranun (Philippines)", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iranun (Philippines)", InvertedName="Iranun (Philippines)")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilp = new DataStandardizer.Language.Iso639Part3Language("ilp");
        
        /// <summary>
        /// International Sign
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("International Sign", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="International Sign", InvertedName="International Sign")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ils = new DataStandardizer.Language.Iso639Part3Language("ils");
        
        /// <summary>
        /// Ili'uun
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ili\'uun", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ili\'uun", InvertedName="Ili\'uun")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilu = new DataStandardizer.Language.Iso639Part3Language("ilu");
        
        /// <summary>
        /// Ilue
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ilue", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ilue", InvertedName="Ilue")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ilv = new DataStandardizer.Language.Iso639Part3Language("ilv");
        
        /// <summary>
        /// Mala Malasar
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Mala Malasar", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Mala Malasar", InvertedName="Malasar, Mala")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ima = new DataStandardizer.Language.Iso639Part3Language("ima");
        
        /// <summary>
        /// Anamgura
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Anamgura", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Anamgura", InvertedName="Anamgura")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @imi = new DataStandardizer.Language.Iso639Part3Language("imi");
        
        /// <summary>
        /// Miluk
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Miluk", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Miluk", InvertedName="Miluk")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iml = new DataStandardizer.Language.Iso639Part3Language("iml");
        
        /// <summary>
        /// Imonda
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Imonda", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Imonda", InvertedName="Imonda")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @imn = new DataStandardizer.Language.Iso639Part3Language("imn");
        
        /// <summary>
        /// Imbongu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Imbongu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Imbongu", InvertedName="Imbongu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @imo = new DataStandardizer.Language.Iso639Part3Language("imo");
        
        /// <summary>
        /// Imroing
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Imroing", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Imroing", InvertedName="Imroing")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @imr = new DataStandardizer.Language.Iso639Part3Language("imr");
        
        /// <summary>
        /// Marsian
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Marsian", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Historical, PrintName="Marsian", InvertedName="Marsian")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ims = new DataStandardizer.Language.Iso639Part3Language("ims");
        
        /// <summary>
        /// Imotong
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Imotong", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Imotong", InvertedName="Imotong")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @imt = new DataStandardizer.Language.Iso639Part3Language("imt");
        
        /// <summary>
        /// Milyan
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Milyan", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Historical, PrintName="Milyan", InvertedName="Milyan")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @imy = new DataStandardizer.Language.Iso639Part3Language("imy");
        
        /// <summary>
        /// Interlingua (International Auxiliary Language Association)
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Interlingua (International Auxiliary Language Association)", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Constructed, PrintName="Interlingua (International Auxiliary Language Association)", InvertedName="Interlingua (International Auxiliary Language Association)", Part1Code="ia", Part2BCode="ina", Part2TCode="ina")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ina = new DataStandardizer.Language.Iso639Part3Language("ina");
        
        /// <summary>
        /// Inga
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inga", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inga", InvertedName="Inga")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inb = new DataStandardizer.Language.Iso639Part3Language("inb");
        
        /// <summary>
        /// Indonesian
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Indonesian", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Indonesian", InvertedName="Indonesian", Part1Code="id", Part2BCode="ind", Part2TCode="ind", MacrolanguageCode="msa")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ind = new DataStandardizer.Language.Iso639Part3Language("ind");
        
        /// <summary>
        /// Degexit'an
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Degexit\'an", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Degexit\'an", InvertedName="Degexit\'an")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ing = new DataStandardizer.Language.Iso639Part3Language("ing");
        
        /// <summary>
        /// Ingush
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ingush", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ingush", InvertedName="Ingush", Part2BCode="inh", Part2TCode="inh")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inh = new DataStandardizer.Language.Iso639Part3Language("inh");
        
        /// <summary>
        /// Jungle Inga
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Jungle Inga", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Jungle Inga", InvertedName="Inga, Jungle")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inj = new DataStandardizer.Language.Iso639Part3Language("inj");
        
        /// <summary>
        /// Indonesian Sign Language
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Indonesian Sign Language", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Indonesian Sign Language", InvertedName="Indonesian Sign Language")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inl = new DataStandardizer.Language.Iso639Part3Language("inl");
        
        /// <summary>
        /// Minaean
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Minaean", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Historical, PrintName="Minaean", InvertedName="Minaean")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inm = new DataStandardizer.Language.Iso639Part3Language("inm");
        
        /// <summary>
        /// Isinai
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isinai", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isinai", InvertedName="Isinai")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inn = new DataStandardizer.Language.Iso639Part3Language("inn");
        
        /// <summary>
        /// Inoke-Yate
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inoke-Yate", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inoke-Yate", InvertedName="Inoke-Yate")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ino = new DataStandardizer.Language.Iso639Part3Language("ino");
        
        /// <summary>
        /// Iñapari
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iñapari", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iñapari", InvertedName="Iñapari")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inp = new DataStandardizer.Language.Iso639Part3Language("inp");
        
        /// <summary>
        /// Indian Sign Language
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Indian Sign Language", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Indian Sign Language", InvertedName="Indian Sign Language")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ins = new DataStandardizer.Language.Iso639Part3Language("ins");
        
        /// <summary>
        /// Intha
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Intha", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Intha", InvertedName="Intha")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @int = new DataStandardizer.Language.Iso639Part3Language("int");
        
        /// <summary>
        /// Ineseño
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ineseño", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Ineseño", InvertedName="Ineseño")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @inz = new DataStandardizer.Language.Iso639Part3Language("inz");
        
        /// <summary>
        /// Inor
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inor", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inor", InvertedName="Inor")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ior = new DataStandardizer.Language.Iso639Part3Language("ior");
        
        /// <summary>
        /// Tuma-Irumu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Tuma-Irumu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Tuma-Irumu", InvertedName="Tuma-Irumu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iou = new DataStandardizer.Language.Iso639Part3Language("iou");
        
        /// <summary>
        /// Iowa-Oto
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iowa-Oto", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Iowa-Oto", InvertedName="Iowa-Oto")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iow = new DataStandardizer.Language.Iso639Part3Language("iow");
        
        /// <summary>
        /// Ipili
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ipili", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ipili", InvertedName="Ipili")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ipi = new DataStandardizer.Language.Iso639Part3Language("ipi");
        
        /// <summary>
        /// Inupiaq
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inupiaq", DataStandardizer.Language.Iso639LanguageScope.Macrolanguage, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inupiaq", InvertedName="Inupiaq", Part1Code="ik", Part2BCode="ipk", Part2TCode="ipk")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ipk = new DataStandardizer.Language.Iso639Part3Language("ipk");
        
        /// <summary>
        /// Ipiko
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ipiko", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ipiko", InvertedName="Ipiko")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ipo = new DataStandardizer.Language.Iso639Part3Language("ipo");
        
        /// <summary>
        /// Iquito
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iquito", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iquito", InvertedName="Iquito")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iqu = new DataStandardizer.Language.Iso639Part3Language("iqu");
        
        /// <summary>
        /// Ikwo
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ikwo", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ikwo", InvertedName="Ikwo")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iqw = new DataStandardizer.Language.Iso639Part3Language("iqw");
        
        /// <summary>
        /// Iresim
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iresim", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iresim", InvertedName="Iresim")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ire = new DataStandardizer.Language.Iso639Part3Language("ire");
        
        /// <summary>
        /// Irarutu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Irarutu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Irarutu", InvertedName="Irarutu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @irh = new DataStandardizer.Language.Iso639Part3Language("irh");
        
        /// <summary>
        /// Rigwe
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Rigwe", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Irigwe Rigwe", InvertedName="Irigwe Rigwe")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iri = new DataStandardizer.Language.Iso639Part3Language("iri");
        
        /// <summary>
        /// Iraqw
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iraqw", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iraqw", InvertedName="Iraqw")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @irk = new DataStandardizer.Language.Iso639Part3Language("irk");
        
        /// <summary>
        /// Irántxe
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Irántxe", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Irántxe", InvertedName="Irántxe")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @irn = new DataStandardizer.Language.Iso639Part3Language("irn");
        
        /// <summary>
        /// Ir
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ir", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ir", InvertedName="Ir")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @irr = new DataStandardizer.Language.Iso639Part3Language("irr");
        
        /// <summary>
        /// Irula
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Irula", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Irula", InvertedName="Irula")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iru = new DataStandardizer.Language.Iso639Part3Language("iru");
        
        /// <summary>
        /// Kamberau
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Kamberau", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Kamberau", InvertedName="Kamberau")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @irx = new DataStandardizer.Language.Iso639Part3Language("irx");
        
        /// <summary>
        /// Iraya
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iraya", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iraya", InvertedName="Iraya")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iry = new DataStandardizer.Language.Iso639Part3Language("iry");
        
        /// <summary>
        /// Isabi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isabi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isabi", InvertedName="Isabi")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isa = new DataStandardizer.Language.Iso639Part3Language("isa");
        
        /// <summary>
        /// Isconahua
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isconahua", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isconahua", InvertedName="Isconahua")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isc = new DataStandardizer.Language.Iso639Part3Language("isc");
        
        /// <summary>
        /// Isnag
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isnag", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isnag", InvertedName="Isnag")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isd = new DataStandardizer.Language.Iso639Part3Language("isd");
        
        /// <summary>
        /// Italian Sign Language
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Italian Sign Language", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Italian Sign Language", InvertedName="Italian Sign Language")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ise = new DataStandardizer.Language.Iso639Part3Language("ise");
        
        /// <summary>
        /// Irish Sign Language
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Irish Sign Language", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Irish Sign Language", InvertedName="Irish Sign Language")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isg = new DataStandardizer.Language.Iso639Part3Language("isg");
        
        /// <summary>
        /// Esan
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Esan", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Esan", InvertedName="Esan")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ish = new DataStandardizer.Language.Iso639Part3Language("ish");
        
        /// <summary>
        /// Nkem-Nkum
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Nkem-Nkum", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Nkem-Nkum", InvertedName="Nkem-Nkum")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isi = new DataStandardizer.Language.Iso639Part3Language("isi");
        
        /// <summary>
        /// Ishkashimi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ishkashimi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ishkashimi", InvertedName="Ishkashimi")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isk = new DataStandardizer.Language.Iso639Part3Language("isk");
        
        /// <summary>
        /// Icelandic
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Icelandic", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Icelandic", InvertedName="Icelandic", Part1Code="is", Part2BCode="ice", Part2TCode="isl")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isl = new DataStandardizer.Language.Iso639Part3Language("isl");
        
        /// <summary>
        /// Masimasi
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Masimasi", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Masimasi", InvertedName="Masimasi")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ism = new DataStandardizer.Language.Iso639Part3Language("ism");
        
        /// <summary>
        /// Isanzu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isanzu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isanzu", InvertedName="Isanzu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isn = new DataStandardizer.Language.Iso639Part3Language("isn");
        
        /// <summary>
        /// Isoko
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isoko", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isoko", InvertedName="Isoko")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iso = new DataStandardizer.Language.Iso639Part3Language("iso");
        
        /// <summary>
        /// Israeli Sign Language
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Israeli Sign Language", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Israeli Sign Language", InvertedName="Israeli Sign Language")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isr = new DataStandardizer.Language.Iso639Part3Language("isr");
        
        /// <summary>
        /// Istriot
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Istriot", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Istriot", InvertedName="Istriot")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ist = new DataStandardizer.Language.Iso639Part3Language("ist");
        
        /// <summary>
        /// Isu (Menchum Division)
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isu (Menchum Division)", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isu (Menchum Division)", InvertedName="Isu (Menchum Division)")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isu = new DataStandardizer.Language.Iso639Part3Language("isu");
        
        /// <summary>
        /// Interslavic
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Interslavic", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Constructed, PrintName="Interslavic", InvertedName="Interslavic")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @isv = new DataStandardizer.Language.Iso639Part3Language("isv");
        
        /// <summary>
        /// Italian
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Italian", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Italian", InvertedName="Italian", Part1Code="it", Part2BCode="ita", Part2TCode="ita")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ita = new DataStandardizer.Language.Iso639Part3Language("ita");
        
        /// <summary>
        /// Binongan Itneg
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Binongan Itneg", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Binongan Itneg", InvertedName="Itneg, Binongan")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itb = new DataStandardizer.Language.Iso639Part3Language("itb");
        
        /// <summary>
        /// Southern Tidung
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Southern Tidung", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Southern Tidung", InvertedName="Tidung, Southern")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itd = new DataStandardizer.Language.Iso639Part3Language("itd");
        
        /// <summary>
        /// Itene
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Itene", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Extinct, PrintName="Itene", InvertedName="Itene")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ite = new DataStandardizer.Language.Iso639Part3Language("ite");
        
        /// <summary>
        /// Inlaod Itneg
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Inlaod Itneg", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Inlaod Itneg", InvertedName="Itneg, Inlaod")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iti = new DataStandardizer.Language.Iso639Part3Language("iti");
        
        /// <summary>
        /// Judeo-Italian
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Judeo-Italian", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Judeo-Italian", InvertedName="Judeo-Italian")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itk = new DataStandardizer.Language.Iso639Part3Language("itk");
        
        /// <summary>
        /// Itelmen
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Itelmen", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Itelmen", InvertedName="Itelmen")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itl = new DataStandardizer.Language.Iso639Part3Language("itl");
        
        /// <summary>
        /// Itu Mbon Uzo
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Itu Mbon Uzo", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Itu Mbon Uzo", InvertedName="Itu Mbon Uzo")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itm = new DataStandardizer.Language.Iso639Part3Language("itm");
        
        /// <summary>
        /// Itonama
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Itonama", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Itonama", InvertedName="Itonama")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ito = new DataStandardizer.Language.Iso639Part3Language("ito");
        
        /// <summary>
        /// Iteri
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iteri", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iteri", InvertedName="Iteri")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itr = new DataStandardizer.Language.Iso639Part3Language("itr");
        
        /// <summary>
        /// Isekiri
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Isekiri", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Isekiri", InvertedName="Isekiri")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @its = new DataStandardizer.Language.Iso639Part3Language("its");
        
        /// <summary>
        /// Maeng Itneg
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Maeng Itneg", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Maeng Itneg", InvertedName="Itneg, Maeng")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itt = new DataStandardizer.Language.Iso639Part3Language("itt");
        
        /// <summary>
        /// Itawit
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Itawit", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Itawit", InvertedName="Itawit")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itv = new DataStandardizer.Language.Iso639Part3Language("itv");
        
        /// <summary>
        /// Ito
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ito", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ito", InvertedName="Ito")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itw = new DataStandardizer.Language.Iso639Part3Language("itw");
        
        /// <summary>
        /// Itik
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Itik", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Itik", InvertedName="Itik")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itx = new DataStandardizer.Language.Iso639Part3Language("itx");
        
        /// <summary>
        /// Moyadan Itneg
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Moyadan Itneg", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Moyadan Itneg", InvertedName="Itneg, Moyadan")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ity = new DataStandardizer.Language.Iso639Part3Language("ity");
        
        /// <summary>
        /// Itzá
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Itzá", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Itzá", InvertedName="Itzá")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @itz = new DataStandardizer.Language.Iso639Part3Language("itz");
        
        /// <summary>
        /// Iu Mien
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iu Mien", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iu Mien", InvertedName="Mien, Iu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ium = new DataStandardizer.Language.Iso639Part3Language("ium");
        
        /// <summary>
        /// Ibatan
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ibatan", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ibatan", InvertedName="Ibatan")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ivb = new DataStandardizer.Language.Iso639Part3Language("ivb");
        
        /// <summary>
        /// Ivatan
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ivatan", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ivatan", InvertedName="Ivatan")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ivv = new DataStandardizer.Language.Iso639Part3Language("ivv");
        
        /// <summary>
        /// I-Wak
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("I-Wak", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="I-Wak", InvertedName="I-Wak")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iwk = new DataStandardizer.Language.Iso639Part3Language("iwk");
        
        /// <summary>
        /// Iwam
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iwam", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iwam", InvertedName="Iwam")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iwm = new DataStandardizer.Language.Iso639Part3Language("iwm");
        
        /// <summary>
        /// Iwur
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iwur", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iwur", InvertedName="Iwur")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iwo = new DataStandardizer.Language.Iso639Part3Language("iwo");
        
        /// <summary>
        /// Sepik Iwam
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Sepik Iwam", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Sepik Iwam", InvertedName="Iwam, Sepik")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iws = new DataStandardizer.Language.Iso639Part3Language("iws");
        
        /// <summary>
        /// Ixcatec
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ixcatec", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ixcatec", InvertedName="Ixcatec")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ixc = new DataStandardizer.Language.Iso639Part3Language("ixc");
        
        /// <summary>
        /// Ixil
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ixil", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ixil", InvertedName="Ixil")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @ixl = new DataStandardizer.Language.Iso639Part3Language("ixl");
        
        /// <summary>
        /// Iyayu
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Iyayu", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Iyayu", InvertedName="Iyayu")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iya = new DataStandardizer.Language.Iso639Part3Language("iya");
        
        /// <summary>
        /// Mesaka
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Mesaka", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Mesaka", InvertedName="Mesaka")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iyo = new DataStandardizer.Language.Iso639Part3Language("iyo");
        
        /// <summary>
        /// Yaka (Congo)
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Yaka (Congo)", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Yaka (Congo)", InvertedName="Yaka (Congo)")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @iyx = new DataStandardizer.Language.Iso639Part3Language("iyx");
        
        /// <summary>
        /// Ingrian
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Ingrian", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Ingrian", InvertedName="Ingrian")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @izh = new DataStandardizer.Language.Iso639Part3Language("izh");
        
        /// <summary>
        /// Kizamani
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Kizamani", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Kizamani", InvertedName="Kizamani")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @izm = new DataStandardizer.Language.Iso639Part3Language("izm");
        
        /// <summary>
        /// Izere
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Izere", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Izere", InvertedName="Izere")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @izr = new DataStandardizer.Language.Iso639Part3Language("izr");
        
        /// <summary>
        /// Izii
        /// </summary>
        [DataStandardizer.Language.Iso639LanguageCodeAttribute("Izii", DataStandardizer.Language.Iso639LanguageScope.Individual, DataStandardizer.Language.Iso639LanguageType.Living, PrintName="Izii", InvertedName="Izii")]
        public static readonly DataStandardizer.Language.Iso639Part3Language @izz = new DataStandardizer.Language.Iso639Part3Language("izz");
        #endregion
    }
}

